.PHONY: check lint typecheck test build serve dev

check: lint typecheck test

lint:
	npm run lint

typecheck:
	npm run typecheck

test:
	npm run test:unit

build:
	npm run build

serve:
	npm run serve

dev: build serve
