//! Tests for the training module.

mod config_pairing_tests;
mod config_tests;
mod early_stopping_tests;
mod importance_tests;
mod labels_tests;
mod model_tests;
mod parallelism_tests;
mod quantize_tests;
mod rng_tests;
mod serde_config_tests;
mod serde_helpers;
mod serde_model_tests;
mod subsampling_tests;
mod train_categorical_tests;
mod train_continue_tests;
mod train_goss_tests;
mod train_helpers;
mod train_knob_tests;
mod train_multiclass_edge_tests;
mod train_multiclass_tests;
mod train_nan_tests;
mod train_quantized_tests;
mod train_ranking_tests;
mod train_regression_tests;
mod train_tests;
mod train_weight_tests;
mod validation_tests;
