"""Rendering the shell script that performs an image build.

Small and deliberately dull. Its only judgment calls are the ones a build
gets wrong quietly:

``set -euo pipefail`` rather than ``set -e``. The build's output is read
through a pipe, and without ``pipefail`` a failed ``apptainer build`` reports
success to the caller -- which is a broken image presented as a good one.

The commit stamp is written on every run. Inheriting a previous build's file
would stamp an image with provenance that is not its own, and a wrong commit
is worse than an absent one: the trainer records absent as null, which is
true, and records wrong as fact.

The cache and tmp directories are required rather than defaulted. Apptainer's
defaults live under ``$HOME``, which on HPC3 is a 50 GB volume, and a
multi-gigabyte build that fills it fails in a way that looks like a build
error rather than a disk error.
"""

from __future__ import annotations

from hpc3.contracts.image_spec import ImageSpec
from hpc3.core.image_layout import COMMIT_NAME, DEFINITION_NAME


def render_build_script(spec: ImageSpec, *, image_name: str) -> str:
    """Render the shell script that builds the image.

    Args:
        spec: The image being built.
        image_name: Filename for the produced ``.sif``.

    Returns:
        Shell source, LF-terminated, to be run from the directory holding the
        rendered definition with the first-party wheels staged in ``wheels/``.
    """
    return (
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "# Generated by hpc3.core.image_build.render_build_script.",
                "# Do not hand-edit.",
                "set -euo pipefail",
                "",
                'HERE="$(cd "$(dirname "$0")" && pwd)"',
                'cd "$HERE"',
                "",
                "if [ ! -d wheels ]; then",
                '    echo "no wheels/ directory beside the definition" >&2',
                "    exit 2",
                "fi",
                "",
                "# Written every run: inheriting a previous build's commit would",
                "# stamp this image with provenance that is not its own.",
                f"printf '%s\\n' {spec['git_commit']!r} > {COMMIT_NAME}",
                "",
                'export APPTAINER_CACHEDIR="${APPTAINER_CACHEDIR:?set a cache dir on /pub}"',
                'export APPTAINER_TMPDIR="${APPTAINER_TMPDIR:?set a tmp dir on /pub}"',
                'mkdir -p "$APPTAINER_CACHEDIR" "$APPTAINER_TMPDIR"',
                "",
                f"apptainer build --force {image_name} {DEFINITION_NAME}",
                "",
                f"sha256sum {image_name}",
            ]
        )
        + "\n"
    )


__all__ = ["render_build_script"]
