"""Rendering the script that verifies an image before it is allowed to exist.

The self-check runs INSIDE the image, where this package is not installed, so
it cannot import anything from here. Generating its source from the same spec
that drives the installation is what keeps the assertions and the thing they
assert about in one document: a definition that installs one torch and a
check that expects another is a disagreement this makes unrepresentable.

VERSIONS COME FROM THE INSTALLATION, NOT FROM A MODULE ATTRIBUTE. This read
``__version__`` until 2026-08-30, which works only for packages that follow
that convention. ``typing_extensions`` does not define one, so the first
image whose entire third-party layer was that single package could not state
a version assertion at all -- and the field is required to be non-empty.
Distribution metadata is the sharper question anyway: it is what pip
resolved, where ``__version__`` is whatever the package chose to write down.

Ordering is the whole value. An image that cannot import its own trainer is
cheap to discover at build time and expensive to discover after a job has
queued, waited for an A100, and died before its first step -- which is what
the DeterminismReport rename actually did to the cluster's wheels.
"""

from __future__ import annotations

from hpc3.contracts.image_spec import ImageSpec, SymbolCheck

_HEADER = (
    '"""Verify the built image before it is allowed to exist.',
    "",
    "Generated by hpc3.core.image_selfcheck.render_selfcheck from an image spec,",
    "so these assertions cannot drift from the installation they check.",
    "",
    "Runs inside the image, where hpc3 is not installed -- hence stdlib only.",
    '"""',
    "",
    "from __future__ import annotations",
    "",
    "import importlib",
    "import importlib.metadata",
    "import sys",
    "",
    "#: What pip actually installed, by canonical distribution name.",
    "#:",
    "#: Asked of the INSTALLATION rather than of a module's ``__version__``,",
    "#: which is a convention and not a guarantee: ``typing_extensions``",
    "#: defines none, so an image whose whole third-party layer was that one",
    "#: package could not state a single version assertion. Distribution",
    "#: metadata is also the sharper question -- it is what pip resolved,",
    "#: where ``__version__`` is whatever the package chose to write down.",
    "_INSTALLED = {",
    '    (_dist.metadata["Name"] or "").lower().replace("_", "-"): _dist.version',
    "    for _dist in importlib.metadata.distributions()",
    "}",
    "",
    "",
    "def _fail(message: str) -> None:",
    '    """Report a failed assertion and stop the build.',
    "",
    "    Args:",
    "        message: What was expected and what was found.",
    "",
    "    Raises:",
    "        SystemExit: Always, with status 1.",
    '    """',
    '    print("image self-check FAILED: " + message, file=sys.stderr)',
    "    raise SystemExit(1)",
    "",
    "",
    "def main() -> int:",
    '    """Run every declared assertion.',
    "",
    "    Returns:",
    "        0 when the image matches its spec.",
    "",
    "    Raises:",
    "        SystemExit: Via ``_fail`` on the first mismatch.",
    '    """',
)

_FOOTER = (
    '    print("image self-check OK")',
    "    return 0",
    "",
    "",
    'if __name__ == "__main__":',
    "    sys.exit(main())",
)


def canonical_distribution(name: str) -> str:
    """Return the name a distribution is looked up by.

    Python packaging treats ``typing_extensions`` and ``typing-extensions``
    as one distribution and compares case-insensitively, so a spec may spell
    a name either way and mean the same thing. Normalised here rather than in
    the generated script, because the script runs in an image where nothing
    but the standard library exists.

    Args:
        name: The name as the spec spells it.

    Returns:
        Lowercase, with underscores as hyphens.
    """
    return name.lower().replace("_", "-")


def _render_version_assertion(package: str, version: str) -> list[str]:
    """Render one version assertion as indented Python statements.

    Args:
        package: Distribution whose installed version is checked.
        version: Exact version the built image must report.

    Returns:
        The statement lines, already indented for a function body. Read from
        distribution metadata rather than from a module's ``__version__``: an
        absent distribution reports itself as such instead of raising
        ``PackageNotFoundError`` out of the check, and a package that defines
        no ``__version__`` -- which ``typing_extensions`` does not -- can
        still be asserted.
    """
    canonical = canonical_distribution(package)
    return [
        f'    _found = _INSTALLED.get({canonical!r}, "<not installed>")',
        f"    if _found != {version!r}:",
        f"        _fail({package!r} + ' is ' + str(_found) + ', expected ' + {version!r})",
    ]


def _render_symbol_assertion(check: SymbolCheck) -> list[str]:
    """Render one symbol assertion as indented Python statements.

    Args:
        check: The module and attribute that must exist in the built image.

    Returns:
        The statement lines, already indented for a function body. A missing
        attribute means a stale wheel was installed, so the message says that
        rather than reporting a bare AttributeError.
    """
    module = check["module"]
    attribute = check["attribute"]
    return [
        f"    _mod = importlib.import_module({module!r})",
        f"    if not hasattr(_mod, {attribute!r}):",
        f"        _fail({module!r} + ' is missing ' + {attribute!r}"
        " + ' -- a stale wheel was baked into this image')",
    ]


def render_selfcheck(spec: ImageSpec) -> str:
    """Render the in-image verification script.

    Args:
        spec: The image being built.

    Returns:
        Python source, LF-terminated, asserting every declared version and
        every declared symbol. It exits non-zero on the first failure, which
        fails the build rather than the first job that uses the image.
    """
    lines = list(_HEADER)
    for package, version in spec["expected_versions"].items():
        lines.extend(_render_version_assertion(package, version))
    for check in spec["required_symbols"]:
        lines.extend(_render_symbol_assertion(check))
    lines.extend(_FOOTER)
    return "\n".join(lines) + "\n"


__all__ = ["canonical_distribution", "render_selfcheck"]
