"""Rendering the Apptainer definition and the pinned requirements beside it.

Two decisions in the emitted text are load-bearing and neither is obvious from
reading it.

The virtualenv is created at the spec's ``env_prefix``, which the image
contract has already refused to place under a bind-mounted root. HPC3 mounts
``/pub`` into every container, so an environment built there would be
replaced at runtime by the host directory and the image's own interpreter
would cease to exist inside its own image.

The first-party wheels install with ``--no-deps``. Every dependency is pinned
in the requirements file above them, and letting a wheel resolve its own would
float a version off the captured set -- which is the drift the image exists to
remove, arriving through the one step that looked harmless.
"""

from __future__ import annotations

from hpc3.contracts.image_spec import ImageSpec
from hpc3.core.image_layout import (
    COMMIT_NAME,
    REQUIREMENTS_NAME,
    SELFCHECK_NAME,
    SPEC_DIR,
    WHEEL_DIR,
)


def render_requirements(spec: ImageSpec) -> str:
    """Render the pinned third-party layer as a pip requirements file.

    Args:
        spec: The image being built.

    Returns:
        The file text, LF-terminated. Extra index URLs come first because pip
        reads them as options applying to the whole file, and a local version
        such as ``torch==2.6.0+cu124`` resolves only once its index is known.
    """
    lines = [f"--extra-index-url {url}" for url in spec["extra_index_urls"]]
    if lines:
        lines.append("")
    lines.extend(spec["requirements"])
    return "\n".join(lines) + "\n"


def _render_post(env: str) -> list[str]:
    """Render the ``%post`` section.

    Args:
        env: Absolute container path receiving the virtualenv.

    Returns:
        The section's lines, including its header.
    """
    return [
        "%post",
        "    set -eu",
        "",
        f"    python -m venv {env}",
        f"    {env}/bin/pip install --no-cache-dir --upgrade pip",
        "",
        "    # Third-party layer, every version pinned by the spec.",
        f"    {env}/bin/pip install --no-cache-dir -r {SPEC_DIR}/{REQUIREMENTS_NAME}",
        "",
        "    # First-party layer. --no-deps because the pins above ARE the",
        "    # captured environment; resolving again would silently move one.",
        f"    {env}/bin/pip install --no-cache-dir --no-deps {WHEEL_DIR}/*.whl",
        "",
        "    # Provenance the trainer stamps into every manifest it writes.",
        f"    cp {SPEC_DIR}/{COMMIT_NAME} {env}/{COMMIT_NAME}",
        "",
        "    # %files preserves the HOST's permissions and %post runs as root,",
        "    # so a file staged mode 640 lands root-owned and unreadable by the",
        "    # unprivileged user who later runs the image. Measured: the first",
        "    # build produced /opt/spec/selfcheck.py as 'nobody nogroup' 640,",
        "    # and re-running the verification failed with EACCES while the",
        "    # environment itself imported fine. An image whose own check",
        "    # cannot be re-run is an image nobody can re-verify, so the modes",
        "    # are set here rather than left to whatever umask staged them.",
        f"    chmod -R a+rX {SPEC_DIR} {env}",
        "",
        "    # Fail the build, not the first job to use the image.",
        f"    {env}/bin/python {SPEC_DIR}/{SELFCHECK_NAME}",
    ]


def render_definition(spec: ImageSpec) -> str:
    """Render the Apptainer definition file.

    Args:
        spec: The image being built.

    Returns:
        The definition text, LF-terminated.
    """
    env = spec["env_prefix"]
    lines = [
        "Bootstrap: docker",
        f"From: {spec['base_image']}",
        "",
        "# Generated by hpc3.core.image_definition.render_definition. Do not",
        "# hand-edit: the self-check shipped alongside is rendered from the same",
        "# spec, and editing one reintroduces the drift an image removes.",
        "",
        "%files",
        f"    {REQUIREMENTS_NAME} {SPEC_DIR}/{REQUIREMENTS_NAME}",
        f"    {SELFCHECK_NAME} {SPEC_DIR}/{SELFCHECK_NAME}",
        f"    {COMMIT_NAME} {SPEC_DIR}/{COMMIT_NAME}",
        f"    wheels {WHEEL_DIR}",
        "",
        *_render_post(env),
        "",
        "%environment",
        f"    export PATH={env}/bin:$PATH",
        "    export PYTHONDONTWRITEBYTECODE=1",
        "",
        "%labels",
        *(f"    {name} {value}" for name, value in spec["labels"].items()),
        "",
        "%help",
        "    Rendered from an hpc3 image spec. Corpora and artifacts are",
        "    bind-mounted, never baked in; their identity is carried by digest",
        "    verification at staging time.",
        "",
        f"    Self-check:  apptainer exec <image> {env}/bin/python {SPEC_DIR}/{SELFCHECK_NAME}",
    ]
    return "\n".join(lines) + "\n"


__all__ = ["render_definition", "render_requirements"]
