"""Rendering the script that verifies an image before it is allowed to exist.

The self-check runs INSIDE the image, where this package is not installed, so
it cannot import anything from here. Generating its source from the same spec
that drives the installation is what keeps the assertions and the thing they
assert about in one document: a definition that installs one torch and a
check that expects another is a disagreement this makes unrepresentable.

VERSIONS COME FROM THE INSTALLATION, NOT FROM A MODULE ATTRIBUTE. This read
``__version__`` until 2026-08-30, which works only for packages that follow
that convention. ``typing_extensions`` does not define one, so the first
image whose entire third-party layer was that single package could not state
a version assertion at all -- and the field is required to be non-empty.
Distribution metadata is the sharper question anyway: it is what pip
resolved, where ``__version__`` is whatever the package chose to write down.

Ordering is the whole value. An image that cannot import its own trainer is
cheap to discover at build time and expensive to discover after a job has
queued, waited for an A100, and died before its first step -- which is what
the DeterminismReport rename actually did to the cluster's wheels.

THE OUTPUT IS SOURCE IN THIS TREE, SO THIS PROJECT'S OWN RULES APPLY TO IT,
and until 2026-09-04 they were broken by construction. Each assertion was
emitted as three inline statements: the ``_fail`` line carried a module name,
an attribute name and a sentence, so a long name pushed it past the column
limit (E501), and ``main`` grew a branch per assertion until a large enough
spec exceeded the complexity ceiling (C901). Across the artifacts on austinpc
that was 871 and 31 of them.

NOBODY COULD SEE IT. Ruff honours ``.gitignore``, these land under an ignored
``runs/``, and ruff applies ``.gitignore`` only inside a git repository -- so
the breach was invisible everywhere except a tree with no ``.git``, which is
exactly one staged onto a build node. Dispatching hpc3 to lavender through
the fleet failed lint with all 902, and ``ruff check . --no-respect-gitignore``
run locally reports the same number, which is what identifies the mechanism
rather than merely suggesting it.

So the spec is rendered as DATA and walked by a loop. The assertions
themselves are written once, in the header, where their length is fixed and
known. ``main`` holds two loops whatever a spec declares, so its complexity is
a constant; and every emitted data line carries one short literal, so no name
a spec can hold puts a line over the limit.
"""

from __future__ import annotations

from hpc3.contracts.image_spec import ImageSpec, SymbolCheck

_HEADER = (
    '"""Verify the built image before it is allowed to exist.',
    "",
    "Generated by hpc3.core.image_selfcheck.render_selfcheck from an image spec,",
    "so these assertions cannot drift from the installation they check.",
    "",
    "Runs inside the image, where hpc3 is not installed -- hence stdlib only.",
    '"""',
    "",
    "from __future__ import annotations",
    "",
    "import importlib",
    "import importlib.metadata",
    "import sys",
    "",
    "#: What pip actually installed, by canonical distribution name.",
    "#:",
    "#: Asked of the INSTALLATION rather than of a module's ``__version__``,",
    "#: which is a convention and not a guarantee: ``typing_extensions``",
    "#: defines none, so an image whose whole third-party layer was that one",
    "#: package could not state a single version assertion. Distribution",
    "#: metadata is also the sharper question -- it is what pip resolved,",
    "#: where ``__version__`` is whatever the package chose to write down.",
    "_INSTALLED = {",
    '    (_dist.metadata["Name"] or "").lower().replace("_", "-"): _dist.version',
    "    for _dist in importlib.metadata.distributions()",
    "}",
    "",
    "",
    "def _fail(message: str) -> None:",
    '    """Report a failed assertion and stop the build.',
    "",
    "    Args:",
    "        message: What was expected and what was found.",
    "",
    "    Raises:",
    "        SystemExit: Always, with status 1.",
    '    """',
    '    print("image self-check FAILED: " + message, file=sys.stderr)',
    "    raise SystemExit(1)",
    "",
    "",
    "def _require_version(package: str, expected: str) -> None:",
    '    """Assert one distribution is installed at one version.',
    "",
    "    Args:",
    "        package: Distribution name, as the spec spells it.",
    "        expected: Exact version the built image must report.",
    "",
    "    Raises:",
    "        SystemExit: Via ``_fail`` when the versions differ.",
    '    """',
    "    # Normalised on the way in, exactly as _INSTALLED's keys were:",
    "    # packaging treats typing_extensions and typing-extensions as one",
    "    # name, so a spec may spell either and mean the same distribution.",
    '    found = _INSTALLED.get(package.lower().replace("_", "-"), "<not installed>")',
    "    if found != expected:",
    '        _fail(package + " is " + found + ", expected " + expected)',
    "",
    "",
    "def _require_symbol(module: str, attribute: str) -> None:",
    '    """Assert one module exports one attribute.',
    "",
    "    Args:",
    "        module: Module to import inside the image.",
    "        attribute: Attribute it must define.",
    "",
    "    Raises:",
    "        SystemExit: Via ``_fail`` when the attribute is absent, which",
    "            means a stale wheel was installed.",
    '    """',
    "    if not hasattr(importlib.import_module(module), attribute):",
    '        _fail(module + " is missing " + attribute',
    '              + " -- a stale wheel was baked into this image")',
    "",
    "",
)

_MAIN = (
    "",
    "def main() -> int:",
    '    """Run every declared assertion.',
    "",
    "    Returns:",
    "        0 when the image matches its spec.",
    "",
    "    Raises:",
    "        SystemExit: Via ``_fail`` on the first mismatch.",
    '    """',
    "    for _package, _expected in _VERSIONS:",
    "        _require_version(_package, _expected)",
    "    for _module, _attribute in _SYMBOLS:",
    "        _require_symbol(_module, _attribute)",
    '    print("image self-check OK")',
    "    return 0",
    "",
    "",
    'if __name__ == "__main__":',
    "    sys.exit(main())",
)


def _render_pair(first: str, second: str) -> list[str]:
    """Render one table entry with each string on a line of its own.

    SPLIT UNCONDITIONALLY rather than only when it would be too long, which
    would require this module to know the column limit its own project
    configures -- a second copy of a number, and the drift it invites is
    precisely the failure this shape exists to remove. One literal per line
    means the only way to exceed the limit is a single name longer than the
    limit, which is a property of the name and would be flagged wherever else
    it was written down.

    Args:
        first: Left-hand value.
        second: Right-hand value.

    Returns:
        The entry's lines, indented for a module-level tuple.
    """
    return [
        "    (",
        f"        {first!r},",
        f"        {second!r},",
        "    ),",
    ]


def _render_table(name: str, entries: list[list[str]]) -> list[str]:
    """Render one module-level tuple of pairs.

    NO EMPTY CASE, because there cannot be one:
    :func:`~hpc3.contracts.image_spec.decode_image_spec` refuses both
    ``expected_versions`` and ``required_symbols`` when empty -- "Field
    'required_symbols' must not be empty" -- so an image always declares at
    least one of each. A branch rendering ``()`` would be unreachable, and
    unreachable code that looks defensive is worse than none: it invites a
    reader to believe the contract is looser than it is.

    Args:
        name: The tuple's name in the generated script.
        entries: Already-rendered entry lines, at least one.

    Returns:
        The assignment's lines.
    """
    lines = [f"{name} = ("]
    for entry in entries:
        lines.extend(entry)
    lines.extend([")", ""])
    return lines


def _render_version_entry(package: str, version: str) -> list[str]:
    """Render one version assertion as a table entry.

    Args:
        package: Distribution whose installed version is checked.
        version: Exact version the built image must report.

    Returns:
        The entry's lines. The name is carried as the SPEC spells it and
        canonicalised inside the generated helper, so the failure message
        names the package the way a reader wrote it while the lookup still
        matches what pip recorded.
    """
    return _render_pair(package, version)


def _render_symbol_entry(check: SymbolCheck) -> list[str]:
    """Render one symbol assertion as a table entry.

    Args:
        check: The module and attribute that must exist in the built image.

    Returns:
        The entry's lines. A missing attribute still reports a stale wheel
        rather than a bare AttributeError -- that message lives in
        ``_require_symbol``, written once.
    """
    return _render_pair(check["module"], check["attribute"])


def render_selfcheck(spec: ImageSpec) -> str:
    """Render the in-image verification script.

    Args:
        spec: The image being built.

    Returns:
        Python source, LF-terminated, asserting every declared version and
        every declared symbol. It exits non-zero on the first failure, which
        fails the build rather than the first job that uses the image.

        The assertions are emitted as DATA and walked by a loop rather than
        unrolled into statements -- see the module docstring for the two lint
        rules the unrolled form broke on its own output, and why nothing
        noticed for as long as it did.
    """
    lines = list(_HEADER)
    lines.extend(
        _render_table(
            "_VERSIONS",
            [
                _render_version_entry(package, version)
                for package, version in spec["expected_versions"].items()
            ],
        )
    )
    lines.extend(
        _render_table(
            "_SYMBOLS", [_render_symbol_entry(check) for check in spec["required_symbols"]]
        )
    )
    lines.extend(_MAIN)
    return "\n".join(lines) + "\n"


__all__ = ["render_selfcheck"]
