"""Rendering the script that verifies an image before it is allowed to exist.

The self-check runs INSIDE the image, where this package is not installed, so
it cannot import anything from here. Generating its source from the same spec
that drives the installation is what keeps the assertions and the thing they
assert about in one document: a definition that installs one torch and a
check that expects another is a disagreement this makes unrepresentable.

Ordering is the whole value. An image that cannot import its own trainer is
cheap to discover at build time and expensive to discover after a job has
queued, waited for an A100, and died before its first step -- which is what
the DeterminismReport rename actually did to the cluster's wheels.
"""

from __future__ import annotations

from hpc3.contracts.image import ImageSpec, SymbolCheck

_HEADER = (
    '"""Verify the built image before it is allowed to exist.',
    "",
    "Generated by hpc3.core.image_selfcheck.render_selfcheck from an image spec,",
    "so these assertions cannot drift from the installation they check.",
    "",
    "Runs inside the image, where hpc3 is not installed -- hence stdlib only.",
    '"""',
    "",
    "from __future__ import annotations",
    "",
    "import importlib",
    "import sys",
    "",
    "",
    "def _fail(message: str) -> None:",
    '    """Report a failed assertion and stop the build.',
    "",
    "    Args:",
    "        message: What was expected and what was found.",
    "",
    "    Raises:",
    "        SystemExit: Always, with status 1.",
    '    """',
    '    print("image self-check FAILED: " + message, file=sys.stderr)',
    "    raise SystemExit(1)",
    "",
    "",
    "def main() -> int:",
    '    """Run every declared assertion.',
    "",
    "    Returns:",
    "        0 when the image matches its spec.",
    "",
    "    Raises:",
    "        SystemExit: Via ``_fail`` on the first mismatch.",
    '    """',
)

_FOOTER = (
    '    print("image self-check OK")',
    "    return 0",
    "",
    "",
    'if __name__ == "__main__":',
    "    sys.exit(main())",
)


def _render_version_assertion(package: str, version: str) -> list[str]:
    """Render one version assertion as indented Python statements.

    Args:
        package: Importable module whose ``__version__`` is checked.
        version: Exact version the built image must report.

    Returns:
        The statement lines, already indented for a function body.
        ``importlib`` is used because the module name is a value from the
        spec, and a value cannot be written as an ``import`` statement.
    """
    return [
        f"    _mod = importlib.import_module({package!r})",
        '    _found = getattr(_mod, "__version__", "<no __version__>")',
        f"    if _found != {version!r}:",
        f"        _fail({package!r} + ' is ' + str(_found) + ', expected ' + {version!r})",
    ]


def _render_symbol_assertion(check: SymbolCheck) -> list[str]:
    """Render one symbol assertion as indented Python statements.

    Args:
        check: The module and attribute that must exist in the built image.

    Returns:
        The statement lines, already indented for a function body. A missing
        attribute means a stale wheel was installed, so the message says that
        rather than reporting a bare AttributeError.
    """
    module = check["module"]
    attribute = check["attribute"]
    return [
        f"    _mod = importlib.import_module({module!r})",
        f"    if not hasattr(_mod, {attribute!r}):",
        f"        _fail({module!r} + ' is missing ' + {attribute!r}"
        " + ' -- a stale wheel was baked into this image')",
    ]


def render_selfcheck(spec: ImageSpec) -> str:
    """Render the in-image verification script.

    Args:
        spec: The image being built.

    Returns:
        Python source, LF-terminated, asserting every declared version and
        every declared symbol. It exits non-zero on the first failure, which
        fails the build rather than the first job that uses the image.
    """
    lines = list(_HEADER)
    for package, version in spec["expected_versions"].items():
        lines.extend(_render_version_assertion(package, version))
    for check in spec["required_symbols"]:
        lines.extend(_render_symbol_assertion(check))
    lines.extend(_FOOTER)
    return "\n".join(lines) + "\n"


__all__ = ["render_selfcheck"]
