"""Reading the project registry from the workspace documents that declare it.

Lifted out of ``hpc3.cli.research_index`` when ``hpc3-register`` became the
second reader. Both must answer "which projects are registered" the SAME way,
because the research index's table is regenerated by each of them: if the two
read the directory differently, a registration could write a table that
``hpc3-research-index --check`` then calls stale, which is the surprise red
check registration is meant to stop producing.

The registry is the set of ``runs/*.json`` documents that carry a ``projects``
table. Nothing else lists it, deliberately: every second list of the projects
-- two in ``test_committed_runs.py``, one in this index's prose -- went stale
and was met as a failing test by whoever registered the next project.
"""

from __future__ import annotations

import pathlib
from typing import Final

from platform_core.errors import AppError, Hpc3ErrorCode
from platform_core.json_utils import JSONValue, load_json_str, narrow_json_to_dict

from hpc3.contracts.project import ProjectConfig
from hpc3.contracts.workspace import (
    WorkspaceConnection,
    decode_workspace,
    decode_workspace_connection,
)
from hpc3.core import _test_hooks

#: The prefix every per-project workspace filename carries.
WORKSPACE_PREFIX: Final[str] = "hpc3-"

#: The suffix every workspace filename carries.
WORKSPACE_SUFFIX: Final[str] = ".json"

#: The first workspace, which predates one-file-per-project and declares
#: ``cleargbm`` rather than a project named after itself.
ORIGINAL_WORKSPACE: Final[str] = "hpc3.json"


def workspace_filename(project: str) -> str:
    """Name the workspace document a project is declared in.

    The ONE statement of the convention ``test_committed_runs.py`` enforces,
    so the command that writes a document and the test that checks it cannot
    disagree about what the file is called.

    Args:
        project: The project's name.

    Returns:
        ``hpc3-<project>.json``.
    """
    return f"{WORKSPACE_PREFIX}{project}{WORKSPACE_SUFFIX}"


def read_document(path: pathlib.Path) -> str:
    """Read a text document with its line endings normalised.

    ``read_bytes`` is the package's file seam and does no newline
    translation, unlike ``pathlib.read_text``. Git checks this repository out
    with CRLF on Windows while the renderers emit LF, so a byte comparison
    reported a document as stale whose every line was already correct -- a
    false verdict that would have had someone rewrite a correct file.

    Args:
        path: The document.

    Returns:
        Its text, with CRLF collapsed to LF.
    """
    return _test_hooks.read_bytes(path).decode("utf-8").replace("\r\n", "\n")


def workspace_documents(runs: pathlib.Path) -> dict[str, dict[str, JSONValue]]:
    """Load every workspace document in a directory.

    A run, sweep or stage document lives beside the workspaces and carries no
    ``projects`` table; that key is what makes a document a workspace.

    Args:
        runs: Directory holding the documents.

    Returns:
        Each workspace's JSON object, keyed by filename, in sorted order.
    """
    loaded: dict[str, dict[str, JSONValue]] = {}
    for path in sorted(runs.glob(f"*{WORKSPACE_SUFFIX}")):
        document = narrow_json_to_dict(load_json_str(read_document(path)))
        if "projects" in document:
            loaded[path.name] = document
    return loaded


def declared_projects(runs: pathlib.Path) -> dict[str, ProjectConfig]:
    """Read every project the workspaces in a directory declare.

    Args:
        runs: Directory holding the workspace documents.

    Returns:
        Every declared project, keyed by name.

    Raises:
        ValueError: If two workspaces declare the same project, which leaves
            no answer to which one governs a run naming it.
    """
    projects: dict[str, ProjectConfig] = {}
    for name, document in workspace_documents(runs).items():
        workspace = decode_workspace(document, config_dir=runs)
        for project, config in workspace["projects"].items():
            if project in projects:
                raise ValueError(f"project {project!r} is declared twice, one place is {name}")
            projects[project] = config
    return projects


def shared_connection(runs: pathlib.Path) -> WorkspaceConnection:
    """Read the connection every workspace in a directory agrees on.

    Decoded against NO directory, so ``ledger`` comes back as written --
    ``ledger.jsonl`` rather than this machine's absolute path to it -- which
    is the form a committed document must carry to work from another clone.

    ``quiet_seconds`` is not part of the agreement: it is a per-document
    triage threshold, and ``hpc3-floor.json`` legitimately carries 600 where
    the rest carry the default.

    Args:
        runs: Directory holding the workspace documents.

    Returns:
        The cluster, host, root and ledger every workspace declares.

    Raises:
        AppError: With ``REGISTRATION_INCOMPLETE`` if the directory holds no
            workspace to agree with, or if two of them name a different
            cluster, host, root or ledger. Picking one would be guessing
            which machine a new project runs on.
    """
    connections = {
        name: decode_workspace_connection(document, config_dir=pathlib.Path())
        for name, document in workspace_documents(runs).items()
    }
    distinct = {
        (c["cluster"], c["host"], c["root"], c["ledger"]): name for name, c in connections.items()
    }
    if len(distinct) != 1:
        raise AppError(
            Hpc3ErrorCode.REGISTRATION_INCOMPLETE,
            f"the workspaces in {runs} must agree on one cluster, host, root and "
            f"ledger for a new document to copy, and they declare {sorted(distinct)} "
            f"(cluster, host, root, ledger) across {sorted(connections)}.",
        )
    return connections[next(iter(distinct.values()))]


__all__ = [
    "ORIGINAL_WORKSPACE",
    "WORKSPACE_PREFIX",
    "WORKSPACE_SUFFIX",
    "declared_projects",
    "read_document",
    "shared_connection",
    "workspace_documents",
    "workspace_filename",
]
