"""Container message decoding module.

This module provides complete container message decoding capabilities,
organized into submodules:

- types: Enums, TypedDicts, decode level registry
- helpers: ContainerDecodeError, validation functions
- identification: Message type identification by structure
- decoders: Message decoding functions organized by category
"""

from __future__ import annotations

from tankpit_bot.container.decoders import (
    DIRECTION_BYTES,
    DIRECTION_EAST,
    DIRECTION_NORTH,
    DIRECTION_SOUTH,
    DIRECTION_WEST,
    SUBTYPE_MOVEMENT,
    SUBTYPE_TANK_REGISTRY,
    decode_chunk_data,
    decode_container_message,
    decode_container_pickup,
    decode_deactivation_death,
    decode_mine_detonation,
    decode_mine_placement,
    decode_player_list_extended,
    decode_player_list_short,
    decode_position_update,
    decode_tank_leave,
    decode_tank_registry,
    decode_tank_status_short,
    decode_tank_update_compact,
    decode_tank_update_full,
    decode_teleport_landed,
    decode_tip_notification,
    decode_unknown_container,
    decode_world_state,
    identify_container_type,
    is_chunk_data_structure,
    is_container_pickup_structure,
    is_deactivation_death_structure,
    is_mine_detonation_structure,
    is_mine_placement_structure,
    is_player_list_extended_structure,
    is_player_list_short_structure,
    is_position_update_structure,
    is_tank_leave_structure,
    is_tank_registry_structure,
    is_tank_status_short_structure,
    is_tank_update_compact_structure,
    is_tank_update_full_structure,
    is_teleport_landed_structure,
    is_tip_notification_structure,
    is_world_state_structure,
)
from tankpit_bot.container.helpers import (
    ContainerDecodeError,
    extract_uint16_le,
    require_exact_length,
    require_length_range,
    require_min_length,
)
from tankpit_bot.container.types import (
    MESSAGE_TYPE_LEVELS,
    ChunkDataDict,
    ContainerMessage,
    ContainerMessageType,
    ContainerPickupDict,
    DeactivationDeathDict,
    DecodeLevel,
    MineDetonationDict,
    MinePlacementDict,
    PlayerListExtendedDict,
    PlayerListShortDict,
    PositionUpdateDict,
    TankLeaveDict,
    TankRegistryDict,
    TankStatusShortDict,
    TankUpdateCompactDict,
    TankUpdateFullDict,
    TeleportLandedDict,
    TipNotificationDict,
    UnknownContainerDict,
    WorldStateDict,
    get_decode_level,
)

__all__ = [
    "DIRECTION_BYTES",
    "DIRECTION_EAST",
    "DIRECTION_NORTH",
    "DIRECTION_SOUTH",
    "DIRECTION_WEST",
    "MESSAGE_TYPE_LEVELS",
    "SUBTYPE_MOVEMENT",
    "SUBTYPE_TANK_REGISTRY",
    "ChunkDataDict",
    "ContainerDecodeError",
    "ContainerMessage",
    "ContainerMessageType",
    "ContainerPickupDict",
    "DeactivationDeathDict",
    "DecodeLevel",
    "MineDetonationDict",
    "MinePlacementDict",
    "PlayerListExtendedDict",
    "PlayerListShortDict",
    "PositionUpdateDict",
    "TankLeaveDict",
    "TankRegistryDict",
    "TankStatusShortDict",
    "TankUpdateCompactDict",
    "TankUpdateFullDict",
    "TeleportLandedDict",
    "TipNotificationDict",
    "UnknownContainerDict",
    "WorldStateDict",
    "decode_chunk_data",
    "decode_container_message",
    "decode_container_pickup",
    "decode_deactivation_death",
    "decode_mine_detonation",
    "decode_mine_placement",
    "decode_player_list_extended",
    "decode_player_list_short",
    "decode_position_update",
    "decode_tank_leave",
    "decode_tank_registry",
    "decode_tank_status_short",
    "decode_tank_update_compact",
    "decode_tank_update_full",
    "decode_teleport_landed",
    "decode_tip_notification",
    "decode_unknown_container",
    "decode_world_state",
    "extract_uint16_le",
    "get_decode_level",
    "identify_container_type",
    "is_chunk_data_structure",
    "is_container_pickup_structure",
    "is_deactivation_death_structure",
    "is_mine_detonation_structure",
    "is_mine_placement_structure",
    "is_player_list_extended_structure",
    "is_player_list_short_structure",
    "is_position_update_structure",
    "is_tank_leave_structure",
    "is_tank_registry_structure",
    "is_tank_status_short_structure",
    "is_tank_update_compact_structure",
    "is_tank_update_full_structure",
    "is_teleport_landed_structure",
    "is_tip_notification_structure",
    "is_world_state_structure",
    "require_exact_length",
    "require_length_range",
    "require_min_length",
]
