"""The equipment atlas: corpus-mined hotspot tiles drive the restock.

Full-corpus mining (2026-08-28, [[equipment-system]]) proved equipment
spawns cluster at persistent per-field hotspots: on practice field01
one center patch recurs in ~100 of 273 archived runs, and 90% of a
fresh session's sightings were already in the previous day's set. The
atlas is that knowledge made operational: a per-field
persistence-weighted tile list (``data/equipment_atlas.json``, built
by ``tankpit-equipment-atlas`` from every archived run), consumed here
as a teleport circuit — hop to the best unvisited hotspot, let the
viewport itself reveal whatever sits there (equipment containers are
plain viewport entities, no radar needed), collect, hop on.

This replaces blind paid quad sweeps as the equipment-discovery
strategy below the radar hunt bar: the 2026-08-28 validation run
burned 9 extras on sweeps that found ZERO equipment on the very field
whose atlas held thousands of mapped tiles.
"""

from __future__ import annotations

import math
from pathlib import Path

from platform_core.json_utils import JSONValue, load_json_str

from tankpit_bot import _test_hooks
from tankpit_bot._test_hooks import TerrainMapProtocol
from tankpit_bot.bot.ai.collect_common import COLLECT_SCORE
from tankpit_bot.bot.ai.context import DecideCtx, make_decision
from tankpit_bot.bot.ai.intent import clear_resource_target
from tankpit_bot.bot.ai.tactics import combat_radar_min
from tankpit_bot.bot.ai.types import AIStateDict
from tankpit_bot.bot.tick_loop_types import TickDecisionDict
from tankpit_bot.bot.types import make_teleport_command
from tankpit_bot.physics.capacity import inventory_capacity
from tankpit_bot.physics.costs import teleport_cost
from tankpit_bot.runtime_logging import emit_ai
from tankpit_bot.sniffer.world_service import WorldService

EQUIPMENT_ATLAS_PATH = Path("data") / "equipment_atlas.json"
"""Committed per-field hotspot data, regenerated by ``make equipment-atlas``."""

ATLAS_VISIT_TTL_MS = 180_000
"""How long a hopped-to (or seen-empty) hotspot stays off the circuit.

Equipment containers sit unclaimed until collected, so an empty
hotspot means someone took it; the TTL lets the circuit come back
after the field has had time to repopulate.
"""

ATLAS_MIN_RUNS = 2
"""Tiles seen in fewer archived runs than this are scatter, not atlas."""


def _parse_atlas_rows(payload: JSONValue, field_image: str) -> list[tuple[int, int, int]]:
    """Narrow one field's atlas rows out of the decoded JSON payload.

    Args:
        payload: Decoded ``equipment_atlas.json`` content.
        field_image: Field image filename keying the atlas.

    Returns:
        ``(x, y, run_count)`` rows for the field, empty when the field
        has no mined data.

    Raises:
        ValueError: If the payload shape is not the atlas contract.
    """
    if not isinstance(payload, dict):
        raise ValueError("equipment atlas root must be an object")
    rows = payload.get(field_image)
    if rows is None:
        return []
    if not isinstance(rows, list):
        raise ValueError(f"equipment atlas field {field_image!r} must hold a list")
    parsed: list[tuple[int, int, int]] = []
    for row in rows:
        if not isinstance(row, list) or len(row) != 3:
            raise ValueError(f"equipment atlas row is not [x, y, runs]: {row!r}")
        x, y, runs = row
        if (
            not isinstance(x, int)
            or not isinstance(y, int)
            or not isinstance(runs, int)
            or isinstance(x, bool)
            or isinstance(y, bool)
            or isinstance(runs, bool)
        ):
            raise ValueError(f"equipment atlas row is not [x, y, runs]: {row!r}")
        parsed.append((x, y, runs))
    return parsed


def atlas_tiles_for(ws: WorldService) -> list[tuple[int, int, int]]:
    """Return the current field's hotspot tiles, loading once per session.

    Args:
        ws: The session's world service (knows the selected room's
            field image and caches the loaded atlas).

    Returns:
        ``(x, y, run_count)`` rows, strongest first.
    """
    if ws.equipment_atlas is None:
        field_image = ws.room_images.get(ws.selected_room or "")
        if field_image is None:
            # No room-list image for this session (sim harnesses, a
            # join before the ROOM_LIST): there is no field to key the
            # atlas by, so there is no atlas.
            ws.equipment_atlas = []
            return ws.equipment_atlas
        payload = load_json_str(_test_hooks.read_text(EQUIPMENT_ATLAS_PATH))
        rows = _parse_atlas_rows(payload, field_image)
        ws.equipment_atlas = [row for row in rows if row[2] >= ATLAS_MIN_RUNS]
    return ws.equipment_atlas


def _equipment_deficient(ctx: DecideCtx) -> bool:
    """Return True when the restock bars are not yet met.

    Mirrors the HUNT-entry readiness the restock exists to reach:
    duals and homings at the rank cap, extra radars at the hunt bar.

    Args:
        ctx: Decision context.

    Returns:
        True when any bar is unmet.
    """
    rank = ctx.self_state["rank"]
    cap = inventory_capacity(rank)
    return (
        ctx.inventory["dual_shots"]["count"] < cap
        or ctx.inventory["homing_shots"]["count"] < cap
        or ctx.inventory["extra_radars"]["count"] < combat_radar_min(rank)
    )


def _prune_visits(ws: WorldService, now_ms: int) -> None:
    """Drop expired visit tombstones.

    Args:
        ws: The session's world service.
        now_ms: Current timestamp.
    """
    ws.atlas_visited = {
        key: ts for key, ts in ws.atlas_visited.items() if now_ms - ts < ATLAS_VISIT_TTL_MS
    }


def _best_hotspot(
    ctx: DecideCtx,
    tiles: list[tuple[int, int, int]],
    terrain: TerrainMapProtocol,
) -> tuple[int, int, int] | None:
    """Pick the highest persistence-per-distance reachable hotspot.

    Args:
        ctx: Decision context.
        tiles: The field's atlas rows.
        terrain: Loaded terrain map (the caller checked presence).

    Returns:
        ``(x, y, run_count)`` of the winning hotspot, or None when no
        unvisited, passable, affordable hotspot remains. Adjacency to
        an empty hotspot tombstones it in passing.
    """
    sx, sy = ctx.self_state["x"], ctx.self_state["y"]
    budget = ctx.fuel - ctx.config["fuel_low_threshold"]
    hostile = ctx.ws.hostile_landing_keys(ctx.timestamp_ms)
    best: tuple[float, int, int, int] | None = None
    for x, y, runs in tiles:
        key = f"{x},{y}"
        if key in ctx.ws.atlas_visited or key in hostile:
            continue
        if not terrain.is_passable(x, y):
            continue
        if teleport_cost(sx, sy, x, y) > budget:
            continue
        distance = math.hypot(x - sx, y - sy)
        if distance <= 2:
            # Standing on (or beside) the hotspot with nothing
            # believed there: the spot is empty right now.
            ctx.ws.atlas_visited[key] = ctx.timestamp_ms
            continue
        score = runs / (1.0 + distance)
        if best is None or score > best[0]:
            best = (score, x, y, runs)
    if best is None:
        return None
    return (best[1], best[2], best[3])


def plan_atlas_equipment_hop(ctx: DecideCtx, base_state: AIStateDict) -> TickDecisionDict | None:
    """Plan a teleport to the best unvisited equipment hotspot.

    Runs in the COLLECT cascade after every known-stock branch
    declined (nothing believed collectible in reach) and BEFORE the
    quad sweep: buying a hop to ground that held equipment in a
    hundred archived sessions beats buying four radars of blind
    reveal. The landing's own viewport shows whatever sits there;
    the hostile-landing evidence and displacement tombstones guard
    the landing choice exactly as for every other teleport.

    Args:
        ctx: Decision context.
        base_state: Base AI state to rewrite for the produced command.

    Returns:
        The hop decision, or None when equipment is not needed, the
        field has no atlas, no affordable unvisited hotspot remains,
        or terrain is not yet loaded.
    """
    if not _equipment_deficient(ctx):
        return None
    if ctx.terrain is None:
        return None
    tiles = atlas_tiles_for(ctx.ws)
    if not tiles:
        return None
    _prune_visits(ctx.ws, ctx.timestamp_ms)
    best = _best_hotspot(ctx, tiles, ctx.terrain)
    if best is None:
        return None
    x, y, runs = best
    sx, sy = ctx.self_state["x"], ctx.self_state["y"]
    ctx.ws.atlas_visited[f"{x},{y}"] = ctx.timestamp_ms
    emit_ai(
        "atlas equipment hop: (%d,%d) seen in %d archived runs, cost %d",
        x,
        y,
        runs,
        teleport_cost(sx, sy, x, y),
    )
    return make_decision(
        make_teleport_command(x, y),
        "COLLECT",
        COLLECT_SCORE,
        x,
        y,
        "atlas_equipment_hop",
        clear_resource_target(base_state),
        ctx.equip,
        reason_context={"atlas_runs": runs},
    )


__all__ = [
    "ATLAS_MIN_RUNS",
    "ATLAS_VISIT_TTL_MS",
    "EQUIPMENT_ATLAS_PATH",
    "atlas_tiles_for",
    "plan_atlas_equipment_hop",
]
