"""Hooks for relaying one fleet child's video to a manager caller.

A fleet child serves ``/video`` on a port of its own inside the
manager's container. Nothing outside that container can dial it, and
nothing should: publishing a port per bot would put the fleet's whole
internal surface on the network to expose one stream. The manager
already answers on the one published port, so it relays instead.

The upstream read sits behind :class:`OpenChildVideoProtocol` for the
same reason every other non-pure operation in this package does —
tests drive the relay against a stream they construct, exercising the
real route, the real response writing and the real teardown, without a
socket.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

import aiohttp


class ChildVideoStreamProtocol(Protocol):
    """One open MJPEG stream, and the means to drain and release it."""

    @property
    def content_type(self) -> str:
        """The upstream's own ``Content-Type``.

        Relayed verbatim rather than reconstructed: the multipart
        boundary token is generated by the child and a caller that
        receives a different one cannot split the frames.

        Returns:
            The upstream content type, boundary included.
        """
        ...

    def chunks(self) -> AsyncIterator[bytes]:
        """Yield body bytes as they arrive, until the upstream ends.

        Returns:
            An iterator over raw response chunks. Frame boundaries are
            NOT respected -- this is a byte relay, and re-framing here
            would mean parsing a stream the caller is about to parse
            again.
        """
        ...

    async def close(self) -> None:
        """Release the upstream connection.

        Called whether the relay finished or the caller disconnected
        mid-frame. A viewer closing a tab is the common case, not an
        exceptional one, and an unreleased upstream would hold a
        connection against the child for the life of the manager.
        """
        ...


class OpenChildVideoProtocol(Protocol):
    """Opens a child's video stream by URL."""

    async def __call__(self, url: str) -> ChildVideoStreamProtocol:
        """Open one upstream stream.

        Args:
            url: Absolute URL of the child's ``/video`` endpoint.

        Returns:
            The open stream.

        Raises:
            aiohttp.ClientError: If the child cannot be reached or
                answers with an error status.
        """
        ...


class _AiohttpChildVideoStream:
    """A :class:`ChildVideoStreamProtocol` over a live aiohttp response."""

    def __init__(self, session: aiohttp.ClientSession, response: aiohttp.ClientResponse) -> None:
        """Bind the stream to the connection it owns.

        The session is owned here, not shared: the relay holds one
        upstream open for as long as one viewer watches, so pooling
        buys nothing and a shared session would outlive the route that
        needs it.

        Args:
            session: The client session to close with this stream.
            response: The open upstream response.
        """
        self._session = session
        self._response = response

    @property
    def content_type(self) -> str:
        """The upstream's own ``Content-Type``.

        Returns:
            The upstream content type, boundary included.
        """
        return self._response.headers["Content-Type"]

    async def chunks(self) -> AsyncIterator[bytes]:
        """Yield body bytes as they arrive.

        Yields:
            Raw response chunks.
        """
        async for chunk in self._response.content.iter_any():
            yield chunk

    async def close(self) -> None:
        """Release the response and the session that carried it."""
        self._response.release()
        await self._session.close()


async def _real_open_child_video(url: str) -> ChildVideoStreamProtocol:
    """Open a child's video stream over HTTP.

    Args:
        url: Absolute URL of the child's ``/video`` endpoint.

    Returns:
        The open stream.

    Raises:
        aiohttp.ClientError: If the child cannot be reached or answers
            with an error status.
    """
    # The session is OWNED here until the stream takes it, and the
    # handover is the last thing that happens. Anything that goes wrong
    # before it — a child that has not bound its port yet, an error
    # status, or the viewer disconnecting mid-await and cancelling the
    # task — leaves this function still holding the connection, so the
    # session is closed on the way out.
    #
    # Not a rare path: a warming child refuses EVERY fresh viewer for
    # its first seconds, and the manager logged an "Unclosed client
    # session" for each one. Expressed as ownership rather than as an
    # ``except`` because that is what it is — nothing here handles a
    # failure, it just declines to leak on one.
    session = aiohttp.ClientSession()
    handed_over = False
    try:
        response = await session.get(url)
        response.raise_for_status()
        stream = _AiohttpChildVideoStream(session, response)
        handed_over = True
        return stream
    finally:
        if not handed_over:
            await session.close()


#: Upstream-open hook — production reads a real child over HTTP; tests
#: substitute a stream whose chunks they control.
open_child_video: OpenChildVideoProtocol = _real_open_child_video


__all__ = [
    "ChildVideoStreamProtocol",
    "OpenChildVideoProtocol",
    "_AiohttpChildVideoStream",
    "_real_open_child_video",
    "open_child_video",
]
