"""Base event schemas for multi-domain streaming platform.

Provides domain-agnostic TypedDict definitions and encoder/decoder functions
for base events shared across all pluggable domains. Domain-specific events
extend these base types with additional fields.

Event types:
- BaseInputEventV1: Minimal input event consumed from Kafka.
- BasePredictionEventV1: Minimal prediction event published to Kafka.
- BaseAlertEventV1: Minimal alert event for high-severity predictions.

Strict typing: no Any, no casts, no type: ignore.
"""

from __future__ import annotations

from typing import Literal, TypedDict

from platform_core.json_utils import (
    JSONTypeError,
    dump_json_str,
    load_json_str,
    narrow_json_to_dict,
    require_float,
    require_int,
    require_str,
)

# =============================================================================
# Shared Type Aliases
# =============================================================================

BaseAlertSeverity = Literal["info", "warning", "critical"]

# =============================================================================
# Input Event: BaseInputEventV1
# =============================================================================


class BaseInputEventV1(TypedDict):
    """Minimal input event consumed from Kafka.

    All domain-specific input events must include these fields.
    Domain implementations extend this with additional domain-specific fields.

    Attributes:
        type: Event type discriminator (domain.event_name.version).
        event_id: UUID for deduplication.
        entity_id: Primary entity identifier (deal_id, match_id, station_id).
        timestamp: ISO datetime when event was emitted.
    """

    type: str
    event_id: str
    entity_id: str
    timestamp: str


# =============================================================================
# Output Event: BasePredictionEventV1
# =============================================================================


class BasePredictionEventV1(TypedDict):
    """Minimal prediction event published to Kafka.

    All domain-specific prediction events must include these fields.

    Attributes:
        type: Event type discriminator.
        event_id: UUID for this event.
        entity_id: Primary entity identifier.
        prediction_value: Primary prediction output (probability, score, etc.).
        confidence: Model confidence in prediction (0.0-1.0).
        model_version: Version string of the ML model used.
        latency_ms: Inference latency in milliseconds.
        processed_at: ISO datetime when processing completed.
    """

    type: str
    event_id: str
    entity_id: str
    prediction_value: float
    confidence: float
    model_version: str
    latency_ms: int
    processed_at: str


# =============================================================================
# Output Event: BaseAlertEventV1
# =============================================================================


class BaseAlertEventV1(TypedDict):
    """Minimal alert event for high-severity predictions.

    Published when a prediction exceeds the domain's alert threshold.
    Contains a human-readable summary generated by Gemini.

    Attributes:
        type: Event type discriminator.
        event_id: UUID for this event.
        entity_id: Primary entity identifier.
        alert_type: Category of alert (domain-specific string).
        severity: Alert severity level.
        prediction_value: Value that triggered the alert.
        gemini_summary: Human-readable summary from Gemini.
        triggered_at: ISO datetime when alert was triggered.
    """

    type: str
    event_id: str
    entity_id: str
    alert_type: str
    severity: BaseAlertSeverity
    prediction_value: float
    gemini_summary: str
    triggered_at: str


# =============================================================================
# Factory Functions
# =============================================================================


def make_base_input_event(
    *,
    type: str,
    event_id: str,
    entity_id: str,
    timestamp: str,
) -> BaseInputEventV1:
    """Create a base input event.

    Args:
        type: Event type discriminator.
        event_id: UUID for deduplication.
        entity_id: Primary entity identifier.
        timestamp: ISO datetime when emitted.

    Returns:
        BaseInputEventV1 instance.
    """
    return {
        "type": type,
        "event_id": event_id,
        "entity_id": entity_id,
        "timestamp": timestamp,
    }


def make_base_prediction_event(
    *,
    type: str,
    event_id: str,
    entity_id: str,
    prediction_value: float,
    confidence: float,
    model_version: str,
    latency_ms: int,
    processed_at: str,
) -> BasePredictionEventV1:
    """Create a base prediction event.

    Args:
        type: Event type discriminator.
        event_id: UUID for this event.
        entity_id: Primary entity identifier.
        prediction_value: Primary prediction output.
        confidence: Model confidence (0.0-1.0).
        model_version: ML model version string.
        latency_ms: Inference latency in milliseconds.
        processed_at: ISO datetime of processing.

    Returns:
        BasePredictionEventV1 instance.
    """
    return {
        "type": type,
        "event_id": event_id,
        "entity_id": entity_id,
        "prediction_value": prediction_value,
        "confidence": confidence,
        "model_version": model_version,
        "latency_ms": latency_ms,
        "processed_at": processed_at,
    }


def make_base_alert_event(
    *,
    type: str,
    event_id: str,
    entity_id: str,
    alert_type: str,
    severity: BaseAlertSeverity,
    prediction_value: float,
    gemini_summary: str,
    triggered_at: str,
) -> BaseAlertEventV1:
    """Create a base alert event.

    Args:
        type: Event type discriminator.
        event_id: UUID for this event.
        entity_id: Primary entity identifier.
        alert_type: Category of alert.
        severity: Alert severity level.
        prediction_value: Value that triggered alert.
        gemini_summary: Human-readable summary from Gemini.
        triggered_at: ISO datetime of alert.

    Returns:
        BaseAlertEventV1 instance.
    """
    return {
        "type": type,
        "event_id": event_id,
        "entity_id": entity_id,
        "alert_type": alert_type,
        "severity": severity,
        "prediction_value": prediction_value,
        "gemini_summary": gemini_summary,
        "triggered_at": triggered_at,
    }


# =============================================================================
# Encoder Functions
# =============================================================================


def encode_base_input_event(event: BaseInputEventV1) -> str:
    """Serialize a base input event to JSON string.

    Args:
        event: BaseInputEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_base_prediction_event(event: BasePredictionEventV1) -> str:
    """Serialize a base prediction event to JSON string.

    Args:
        event: BasePredictionEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_base_alert_event(event: BaseAlertEventV1) -> str:
    """Serialize a base alert event to JSON string.

    Args:
        event: BaseAlertEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


# =============================================================================
# Literal Type Parsers
# =============================================================================


def _parse_base_alert_severity(raw: str) -> BaseAlertSeverity:
    """Parse base alert severity from string.

    Args:
        raw: Raw string value.

    Returns:
        Validated BaseAlertSeverity literal.

    Raises:
        JSONTypeError: If value is not a valid severity.
    """
    if raw == "info":
        return "info"
    if raw == "warning":
        return "warning"
    if raw == "critical":
        return "critical"
    raise JSONTypeError(f"Invalid base alert severity '{raw}'")


# =============================================================================
# Decoder Functions
# =============================================================================


def decode_base_input_event(payload: str) -> BaseInputEventV1:
    """Parse and validate a base input event from JSON string.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated BaseInputEventV1.

    Raises:
        JSONTypeError: If required fields are missing or invalid.
        InvalidJsonError: If payload is not valid JSON.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    event_type = require_str(decoded, "type")
    event_id = require_str(decoded, "event_id")
    entity_id = require_str(decoded, "entity_id")
    timestamp = require_str(decoded, "timestamp")
    return {
        "type": event_type,
        "event_id": event_id,
        "entity_id": entity_id,
        "timestamp": timestamp,
    }


def decode_base_prediction_event(payload: str) -> BasePredictionEventV1:
    """Parse and validate a base prediction event from JSON string.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated BasePredictionEventV1.

    Raises:
        JSONTypeError: If required fields are missing or invalid.
        InvalidJsonError: If payload is not valid JSON.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    event_type = require_str(decoded, "type")
    event_id = require_str(decoded, "event_id")
    entity_id = require_str(decoded, "entity_id")
    prediction_value = require_float(decoded, "prediction_value")
    confidence = require_float(decoded, "confidence")
    model_version = require_str(decoded, "model_version")
    latency_ms = require_int(decoded, "latency_ms")
    processed_at = require_str(decoded, "processed_at")
    return {
        "type": event_type,
        "event_id": event_id,
        "entity_id": entity_id,
        "prediction_value": prediction_value,
        "confidence": confidence,
        "model_version": model_version,
        "latency_ms": latency_ms,
        "processed_at": processed_at,
    }


def decode_base_alert_event(payload: str) -> BaseAlertEventV1:
    """Parse and validate a base alert event from JSON string.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated BaseAlertEventV1.

    Raises:
        JSONTypeError: If required fields are missing or invalid.
        InvalidJsonError: If payload is not valid JSON.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    event_type = require_str(decoded, "type")
    event_id = require_str(decoded, "event_id")
    entity_id = require_str(decoded, "entity_id")
    alert_type = require_str(decoded, "alert_type")
    severity_raw = require_str(decoded, "severity")
    severity = _parse_base_alert_severity(severity_raw)
    prediction_value = require_float(decoded, "prediction_value")
    gemini_summary = require_str(decoded, "gemini_summary")
    triggered_at = require_str(decoded, "triggered_at")
    return {
        "type": event_type,
        "event_id": event_id,
        "entity_id": entity_id,
        "alert_type": alert_type,
        "severity": severity,
        "prediction_value": prediction_value,
        "gemini_summary": gemini_summary,
        "triggered_at": triggered_at,
    }


__all__ = [
    "BaseAlertEventV1",
    "BaseAlertSeverity",
    "BaseInputEventV1",
    "BasePredictionEventV1",
    "decode_base_alert_event",
    "decode_base_input_event",
    "decode_base_prediction_event",
    "encode_base_alert_event",
    "encode_base_input_event",
    "encode_base_prediction_event",
    "make_base_alert_event",
    "make_base_input_event",
    "make_base_prediction_event",
]
