"""XGBoost wrapper for covenant breach risk prediction."""

from __future__ import annotations

from .features import (
    EngineeredFeatures,
    FeatureEngineeringConfig,
    FeaturePreset,
    compute_log_transforms,
    compute_pairwise_products,
    compute_pairwise_ratios,
    default_feature_config,
    engineer_features,
    get_feature_config_for_preset,
)
from .manifest import (
    ClassifierManifest,
    ManifestDataset,
    ManifestMetrics,
    ManifestSystem,
    ManifestTraining,
    ManifestVersions,
)
from .metrics import (
    compute_accuracy,
    compute_all_metrics,
    compute_auc,
    compute_f1_score,
    compute_log_loss,
    compute_precision,
    compute_recall,
    format_metrics_str,
)
from .predictor import load_model, predict_probabilities
from .trainer import (
    DataSplits,
    ProgressCallback,
    save_model,
    stratified_split,
    train_model,
    train_model_with_validation,
)
from .types import (
    EvalMetrics,
    FeatureImportance,
    Proba2DProtocol,
    TrainConfig,
    TrainOutcome,
    TrainProgress,
    XGBBoosterProtocol,
    XGBClassifierFactory,
    XGBClassifierLoader,
    XGBModelProtocol,
)

__all__ = [
    "ClassifierManifest",
    "DataSplits",
    "EngineeredFeatures",
    "EvalMetrics",
    "FeatureEngineeringConfig",
    "FeatureImportance",
    "FeaturePreset",
    "ManifestDataset",
    "ManifestMetrics",
    "ManifestSystem",
    "ManifestTraining",
    "ManifestVersions",
    "Proba2DProtocol",
    "ProgressCallback",
    "TrainConfig",
    "TrainOutcome",
    "TrainProgress",
    "XGBBoosterProtocol",
    "XGBClassifierFactory",
    "XGBClassifierLoader",
    "XGBModelProtocol",
    "compute_accuracy",
    "compute_all_metrics",
    "compute_auc",
    "compute_f1_score",
    "compute_log_loss",
    "compute_log_transforms",
    "compute_pairwise_products",
    "compute_pairwise_ratios",
    "compute_precision",
    "compute_recall",
    "default_feature_config",
    "engineer_features",
    "format_metrics_str",
    "get_feature_config_for_preset",
    "load_model",
    "predict_probabilities",
    "save_model",
    "stratified_split",
    "train_model",
    "train_model_with_validation",
]
