"""Integration tests for doc_extract_api against corvis_test database.

These tests connect to the real corvis_test Postgres database
to verify document insertion, page storage, and dedup logic.
Requires DATABASE_TEST_URL in the MCPs repo .env file.
"""

from __future__ import annotations

import io
import os
import tempfile
from pathlib import Path
from typing import Protocol

import pytest
from platform_core.config import _test_hooks as platform_hooks

from doc_extract_api._test_hooks import (
    DbConnection,
    _default_connect_db,
    _default_pdfplumber_open,
    _default_read_file,
    _default_redis_for_kv,
)
from doc_extract_api.db import document_exists, insert_document, insert_pages_batch
from doc_extract_api.types import decode_extracted_page

_TEST_TENANT_ID = "00000000-0000-0000-0000-000000000099"


def _load_test_dsn() -> str:
    """Load DATABASE_TEST_URL from the MCPs .env file.

    Returns:
        Postgres connection string for corvis_test.

    Raises:
        pytest.skip: If DATABASE_TEST_URL is not available.
    """
    # Try the platform config hook first
    get_env = platform_hooks.get_env
    dsn = get_env("DATABASE_TEST_URL")
    if dsn is not None and len(dsn) > 0:
        return dsn

    # Walk up to find the MCPs .env file
    current = Path(__file__).resolve().parent
    for _ in range(10):
        env_file = current / ".env"
        if env_file.exists():
            for line in env_file.read_text(encoding="utf-8").splitlines():
                if line.startswith("DATABASE_TEST_URL="):
                    return line.split("=", 1)[1].strip()
        current = current.parent

    return pytest.skip("DATABASE_TEST_URL not found")


class TestIntegrationDb:
    """Integration tests that hit the real corvis_test database."""

    def _connect(self) -> DbConnection:
        """Create a connection to corvis_test and set tenant context.

        Returns:
            An open database connection with tenant context set.
        """
        dsn = _load_test_dsn()
        conn = _default_connect_db(dsn)
        conn.execute(f"SET app.tenant_id = '{_TEST_TENANT_ID}'")
        return conn

    def test_connect_db_default(self) -> None:
        """_default_connect_db connects to the real test database."""
        conn = self._connect()
        cursor = conn.execute("SELECT 1")
        row = cursor.fetchone()
        assert row is not None and row[0] == 1
        conn.close()

    def test_insert_and_check_document(self) -> None:
        """Insert a document, verify it exists, then clean up."""
        conn = self._connect()
        title = "test-integration-doc-extract-api"
        category = "general"

        # Clean up any leftovers from prior runs
        conn.execute(
            "DELETE FROM document_pages WHERE document_id IN "
            "(SELECT id FROM documents WHERE title = %s AND category = %s)",
            (title, category),
        )
        conn.execute(
            "DELETE FROM documents WHERE title = %s AND category = %s",
            (title, category),
        )
        conn.commit()

        assert document_exists(conn, title, category) is False

        doc_id = insert_document(conn, title, "integration-test", 2, category)
        assert len(doc_id) == 36  # UUID length

        assert document_exists(conn, title, category) is True

        pages = [
            decode_extracted_page(1, "page one content", "pdfplumber-text"),
            decode_extracted_page(2, "page two content", "doctr-ocr"),
        ]
        count = insert_pages_batch(conn, doc_id, pages)
        assert count == 2

        # Clean up
        conn.execute("DELETE FROM document_pages WHERE document_id = %s::uuid", (doc_id,))
        conn.execute("DELETE FROM documents WHERE id = %s::uuid", (doc_id,))
        conn.commit()
        conn.close()


class TestIntegrationPdfplumber:
    """Integration tests for pdfplumber production default."""

    def test_pdfplumber_open_with_real_pdf(self) -> None:
        """_default_pdfplumber_open opens a real PDF generated by fpdf2."""
        _fpdf2 = __import__("fpdf", fromlist=["FPDF"])

        class _FpdfProto(Protocol):
            def add_page(self) -> None: ...
            def set_font(self, family: str, size: int) -> None: ...
            def cell(self, text: str) -> None: ...
            def output(self) -> bytes: ...

        fpdf: _FpdfProto = _fpdf2.FPDF()
        fpdf.add_page()
        fpdf.set_font("Helvetica", size=12)
        fpdf.cell(text="integration test page")
        pdf_bytes: bytes = fpdf.output()

        pdf = _default_pdfplumber_open(io.BytesIO(pdf_bytes))
        assert len(pdf.pages) == 1
        text = pdf.pages[0].extract_text()
        assert text is not None and "integration test page" in text
        pdf.close()


class TestIntegrationReadFile:
    """Integration tests for file reading production default."""

    def test_read_file_default(self) -> None:
        """_default_read_file reads a real file."""
        fd, path = tempfile.mkstemp(suffix=".txt")
        os.write(fd, b"integration test content")
        os.close(fd)
        result = _default_read_file(path)
        assert result == b"integration test content"
        os.unlink(path)


class TestIntegrationRedis:
    """Integration tests for Redis production default."""

    def test_redis_for_kv_connects(self) -> None:
        """_default_redis_for_kv creates a real Redis client."""
        redis = _default_redis_for_kv("redis://127.0.0.1:6379/0")
        result = redis.ping()
        assert result is True
        redis.close()
