"""Kafka event schemas for streaming pipeline.

This module provides TypedDict definitions and encoder/decoder functions
for Kafka events used in the streaming inference pipeline.

Event types:
- MeasurementEventV1: Input measurement events from Kafka
- PredictionEventV1: Output prediction events to Kafka
- AlertEventV1: High-severity alert events with Gemini text

Strict typing: no Any, no casts, no type: ignore.
"""

from __future__ import annotations

from typing import Literal, TypedDict

from platform_core.json_utils import (
    dump_json_str,
)

# =============================================================================
# Event Type Discriminators
# =============================================================================


KafkaEventType = Literal[
    "covenant.measurement.v1",
    "covenant.prediction.v1",
    "covenant.alert.v1",
]

MeasurementEventType = Literal["covenant.measurement.v1"]

PredictionEventType = Literal["covenant.prediction.v1"]

AlertEventType = Literal["covenant.alert.v1"]

# =============================================================================
# Shared Type Aliases
# =============================================================================

# The tier names are declared once in platform_core.risk_tiers; annotations
# spell the Literal inline and the risk-tier guard holds them to that tuple.


AlertType = Literal["breach", "high_risk"]

AlertSeverity = Literal["warning", "critical"]

# =============================================================================
# Input Event: MeasurementEventV1
# =============================================================================


class MeasurementEventV1(TypedDict):
    """Single measurement event consumed from Kafka.

    This event represents a single metric measurement for a deal during a
    specific period. Multiple measurements are aggregated before evaluation.

    Fields:
        type: Event type discriminator.
        event_id: UUID for deduplication.
        deal_id: Deal identifier (partition key).
        period_start: ISO date (YYYY-MM-DD) for period start.
        period_end: ISO date (YYYY-MM-DD) for period end.
        metric_name: Metric identifier (e.g., "debt_to_equity", "ebitda").
        metric_value: Numeric value of the metric.
        timestamp: ISO datetime when event was emitted.
    """

    type: MeasurementEventType
    event_id: str
    deal_id: str
    period_start: str
    period_end: str
    metric_name: str
    metric_value: float
    timestamp: str


# =============================================================================
# Output Event: PredictionEventV1
# =============================================================================


class PredictionEventV1(TypedDict):
    """Risk prediction event published to Kafka.

    Contains both deterministic covenant evaluation results and ML prediction
    for a deal during a specific period.

    Fields:
        type: Event type discriminator.
        event_id: UUID for this event.
        deal_id: Deal identifier (partition key).
        period_start: ISO date (YYYY-MM-DD) for period start.
        period_end: ISO date (YYYY-MM-DD) for period end.
        evaluation_status: Deterministic covenant evaluation result.
        covenants_evaluated: Number of covenants checked.
        breaches_count: Number of covenant breaches detected.
        risk_probability: ML-predicted probability of default (0.0-1.0).
        risk_tier: Categorized risk level based on probability.
        model_version: Version string of the ML model used.
        evaluation_latency_ms: Time spent on deterministic evaluation.
        prediction_latency_ms: Time spent on ML inference.
        processed_at: ISO datetime when processing completed.
    """

    type: PredictionEventType
    event_id: str
    deal_id: str
    period_start: str
    period_end: str
    evaluation_status: Literal["OK", "BREACH", "WARNING"]
    covenants_evaluated: int
    breaches_count: int
    risk_probability: float
    risk_tier: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    model_version: str
    evaluation_latency_ms: int
    prediction_latency_ms: int
    processed_at: str


# =============================================================================
# Output Event: AlertEventV1
# =============================================================================


class AlertEventV1(TypedDict):
    """High-severity alert event with Gemini-generated summary.

    Published when risk exceeds threshold (> 0.8) or covenant breach occurs.
    Contains human-readable summary text generated by Gemini.

    Fields:
        type: Event type discriminator.
        event_id: UUID for this event.
        deal_id: Deal identifier (partition key).
        alert_type: Category of alert (breach or high_risk).
        severity: Alert severity level.
        risk_probability: ML-predicted probability that triggered alert.
        gemini_summary: Human-readable 1-sentence summary from Gemini.
        triggered_at: ISO datetime when alert was triggered.
    """

    type: AlertEventType
    event_id: str
    deal_id: str
    alert_type: AlertType
    severity: AlertSeverity
    risk_probability: float
    gemini_summary: str
    triggered_at: str


DlqEventType = Literal["covenant.dlq.v1"]

# Why a message could not be processed. Specific rather than one generic
# "error", so a consumer of the dead-letter topic can triage without parsing
# free text.
DlqReason = Literal[
    "undecodable_payload",
    "unknown_deal",
]


class DlqEventV1(TypedDict):
    """A measurement that could not be processed, with why.

    Carries the original payload verbatim so the message can be inspected or
    replayed after the cause is fixed. Publishing this is what allows the
    consumer to advance past a message it cannot handle; without it the same
    message is redelivered forever.

    Fields:
        type: Event type discriminator.
        event_id: UUID for this dead-letter record.
        reason: Machine-readable cause.
        detail: Human-readable explanation, including the originating message.
        source_topic: Topic the original message came from.
        source_partition: Partition of the original message.
        source_offset: Offset of the original message.
        payload: Original message payload, decoded as UTF-8 with replacement
            for any invalid bytes so the envelope is always serialisable.
        failed_at: ISO datetime when the failure was recorded.
    """

    type: DlqEventType
    event_id: str
    reason: DlqReason
    detail: str
    source_topic: str
    source_partition: int
    source_offset: int
    payload: str
    failed_at: str


def make_dlq_event(
    event_id: str,
    reason: DlqReason,
    detail: str,
    source_topic: str,
    source_partition: int,
    source_offset: int,
    payload: str,
    failed_at: str,
) -> DlqEventV1:
    """Build a dead-letter event.

    Args:
        event_id: UUID for this dead-letter record.
        reason: Machine-readable cause.
        detail: Human-readable explanation.
        source_topic: Topic the original message came from.
        source_partition: Partition of the original message.
        source_offset: Offset of the original message.
        payload: Original message payload as text.
        failed_at: ISO datetime when the failure was recorded.

    Returns:
        A populated DlqEventV1.
    """
    return {
        "type": "covenant.dlq.v1",
        "event_id": event_id,
        "reason": reason,
        "detail": detail,
        "source_topic": source_topic,
        "source_partition": source_partition,
        "source_offset": source_offset,
        "payload": payload,
        "failed_at": failed_at,
    }


def encode_dlq_event(event: DlqEventV1) -> str:
    """Serialize a dead-letter event to JSON string.

    Args:
        event: DlqEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


# =============================================================================
# Union Type for All Events
# =============================================================================


KafkaEventV1 = MeasurementEventV1 | PredictionEventV1 | AlertEventV1


# =============================================================================
# Factory Functions
# =============================================================================


def make_measurement_event(
    *,
    event_id: str,
    deal_id: str,
    period_start: str,
    period_end: str,
    metric_name: str,
    metric_value: float,
    timestamp: str,
) -> MeasurementEventV1:
    """Create a measurement event.

    Args:
        event_id: UUID for deduplication.
        deal_id: Deal identifier.
        period_start: ISO date for period start.
        period_end: ISO date for period end.
        metric_name: Metric identifier.
        metric_value: Numeric value.
        timestamp: ISO datetime when emitted.

    Returns:
        MeasurementEventV1 instance.
    """
    return {
        "type": "covenant.measurement.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "period_start": period_start,
        "period_end": period_end,
        "metric_name": metric_name,
        "metric_value": metric_value,
        "timestamp": timestamp,
    }


def make_prediction_event(
    *,
    event_id: str,
    deal_id: str,
    period_start: str,
    period_end: str,
    evaluation_status: Literal["OK", "BREACH", "WARNING"],
    covenants_evaluated: int,
    breaches_count: int,
    risk_probability: float,
    risk_tier: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"],
    model_version: str,
    evaluation_latency_ms: int,
    prediction_latency_ms: int,
    processed_at: str,
) -> PredictionEventV1:
    """Create a prediction event.

    Args:
        event_id: UUID for this event.
        deal_id: Deal identifier.
        period_start: ISO date for period start.
        period_end: ISO date for period end.
        evaluation_status: Deterministic evaluation result.
        covenants_evaluated: Number of covenants checked.
        breaches_count: Number of breaches detected.
        risk_probability: ML-predicted probability.
        risk_tier: Categorized risk level.
        model_version: ML model version.
        evaluation_latency_ms: Evaluation time in ms.
        prediction_latency_ms: Prediction time in ms.
        processed_at: ISO datetime of processing.

    Returns:
        PredictionEventV1 instance.
    """
    return {
        "type": "covenant.prediction.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "period_start": period_start,
        "period_end": period_end,
        "evaluation_status": evaluation_status,
        "covenants_evaluated": covenants_evaluated,
        "breaches_count": breaches_count,
        "risk_probability": risk_probability,
        "risk_tier": risk_tier,
        "model_version": model_version,
        "evaluation_latency_ms": evaluation_latency_ms,
        "prediction_latency_ms": prediction_latency_ms,
        "processed_at": processed_at,
    }


def make_alert_event(
    *,
    event_id: str,
    deal_id: str,
    alert_type: AlertType,
    severity: AlertSeverity,
    risk_probability: float,
    gemini_summary: str,
    triggered_at: str,
) -> AlertEventV1:
    """Create an alert event.

    Args:
        event_id: UUID for this event.
        deal_id: Deal identifier.
        alert_type: Category of alert.
        severity: Alert severity level.
        risk_probability: ML-predicted probability.
        gemini_summary: Human-readable summary.
        triggered_at: ISO datetime of alert.

    Returns:
        AlertEventV1 instance.
    """
    return {
        "type": "covenant.alert.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "alert_type": alert_type,
        "severity": severity,
        "risk_probability": risk_probability,
        "gemini_summary": gemini_summary,
        "triggered_at": triggered_at,
    }


# =============================================================================
# Encoder Functions
# =============================================================================


def encode_measurement_event(event: MeasurementEventV1) -> str:
    """Serialize a measurement event to JSON string.

    Args:
        event: MeasurementEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_prediction_event(event: PredictionEventV1) -> str:
    """Serialize a prediction event to JSON string.

    Args:
        event: PredictionEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_alert_event(event: AlertEventV1) -> str:
    """Serialize an alert event to JSON string.

    Args:
        event: AlertEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_kafka_event(event: KafkaEventV1) -> str:
    """Serialize any Kafka event to JSON string.

    Args:
        event: Any KafkaEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


__all__ = [
    "AlertEventType",
    "AlertEventV1",
    "AlertSeverity",
    "AlertType",
    "DlqEventType",
    "DlqEventV1",
    "DlqReason",
    "KafkaEventType",
    "KafkaEventV1",
    "MeasurementEventType",
    "MeasurementEventV1",
    "PredictionEventType",
    "PredictionEventV1",
    "encode_alert_event",
    "encode_dlq_event",
    "encode_kafka_event",
    "encode_measurement_event",
    "encode_prediction_event",
    "make_alert_event",
    "make_dlq_event",
    "make_measurement_event",
    "make_prediction_event",
]
