"""Kafka event schemas for streaming pipeline.

This module provides TypedDict definitions and encoder/decoder functions
for Kafka events used in the streaming inference pipeline.

Event types:
- MeasurementEventV1: Input measurement events from Kafka
- PredictionEventV1: Output prediction events to Kafka
- AlertEventV1: High-severity alert events with Gemini text

Strict typing: no Any, no casts, no type: ignore.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Literal, TypedDict, TypeGuard

from covenant_domain.features import RiskTier, classify_risk_tier
from platform_core.json_utils import (
    JSONObject,
    JSONTypeError,
    dump_json_str,
    load_json_str,
    narrow_json_to_dict,
    require_float,
    require_int,
    require_str,
)

# =============================================================================
# Event Type Discriminators
# =============================================================================

MeasurementEventType = Literal["covenant.measurement.v1"]
PredictionEventType = Literal["covenant.prediction.v1"]
AlertEventType = Literal["covenant.alert.v1"]

KafkaEventType = Literal[
    "covenant.measurement.v1",
    "covenant.prediction.v1",
    "covenant.alert.v1",
]

# =============================================================================
# Shared Type Aliases
# =============================================================================

EvaluationStatus = Literal["OK", "BREACH", "WARNING"]
# RiskTier is imported from covenant_domain.features (single source of truth)
AlertType = Literal["breach", "high_risk"]
AlertSeverity = Literal["warning", "critical"]

# =============================================================================
# Input Event: MeasurementEventV1
# =============================================================================


class MeasurementEventV1(TypedDict):
    """Single measurement event consumed from Kafka.

    This event represents a single metric measurement for a deal during a
    specific period. Multiple measurements are aggregated before evaluation.

    Fields:
        type: Event type discriminator.
        event_id: UUID for deduplication.
        deal_id: Deal identifier (partition key).
        period_start: ISO date (YYYY-MM-DD) for period start.
        period_end: ISO date (YYYY-MM-DD) for period end.
        metric_name: Metric identifier (e.g., "debt_to_equity", "ebitda").
        metric_value: Numeric value of the metric.
        timestamp: ISO datetime when event was emitted.
    """

    type: MeasurementEventType
    event_id: str
    deal_id: str
    period_start: str
    period_end: str
    metric_name: str
    metric_value: float
    timestamp: str


# =============================================================================
# Output Event: PredictionEventV1
# =============================================================================


class PredictionEventV1(TypedDict):
    """Risk prediction event published to Kafka.

    Contains both deterministic covenant evaluation results and ML prediction
    for a deal during a specific period.

    Fields:
        type: Event type discriminator.
        event_id: UUID for this event.
        deal_id: Deal identifier (partition key).
        period_start: ISO date (YYYY-MM-DD) for period start.
        period_end: ISO date (YYYY-MM-DD) for period end.
        evaluation_status: Deterministic covenant evaluation result.
        covenants_evaluated: Number of covenants checked.
        breaches_count: Number of covenant breaches detected.
        risk_probability: ML-predicted probability of default (0.0-1.0).
        risk_tier: Categorized risk level based on probability.
        model_version: Version string of the ML model used.
        evaluation_latency_ms: Time spent on deterministic evaluation.
        prediction_latency_ms: Time spent on ML inference.
        processed_at: ISO datetime when processing completed.
    """

    type: PredictionEventType
    event_id: str
    deal_id: str
    period_start: str
    period_end: str
    evaluation_status: EvaluationStatus
    covenants_evaluated: int
    breaches_count: int
    risk_probability: float
    risk_tier: RiskTier
    model_version: str
    evaluation_latency_ms: int
    prediction_latency_ms: int
    processed_at: str


# =============================================================================
# Output Event: AlertEventV1
# =============================================================================


class AlertEventV1(TypedDict):
    """High-severity alert event with Gemini-generated summary.

    Published when risk exceeds threshold (> 0.8) or covenant breach occurs.
    Contains human-readable summary text generated by Gemini.

    Fields:
        type: Event type discriminator.
        event_id: UUID for this event.
        deal_id: Deal identifier (partition key).
        alert_type: Category of alert (breach or high_risk).
        severity: Alert severity level.
        risk_probability: ML-predicted probability that triggered alert.
        gemini_summary: Human-readable 1-sentence summary from Gemini.
        triggered_at: ISO datetime when alert was triggered.
    """

    type: AlertEventType
    event_id: str
    deal_id: str
    alert_type: AlertType
    severity: AlertSeverity
    risk_probability: float
    gemini_summary: str
    triggered_at: str


# =============================================================================
# Union Type for All Events
# =============================================================================

KafkaEventV1 = MeasurementEventV1 | PredictionEventV1 | AlertEventV1

# =============================================================================
# Factory Functions
# =============================================================================


def make_measurement_event(
    *,
    event_id: str,
    deal_id: str,
    period_start: str,
    period_end: str,
    metric_name: str,
    metric_value: float,
    timestamp: str,
) -> MeasurementEventV1:
    """Create a measurement event.

    Args:
        event_id: UUID for deduplication.
        deal_id: Deal identifier.
        period_start: ISO date for period start.
        period_end: ISO date for period end.
        metric_name: Metric identifier.
        metric_value: Numeric value.
        timestamp: ISO datetime when emitted.

    Returns:
        MeasurementEventV1 instance.
    """
    return {
        "type": "covenant.measurement.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "period_start": period_start,
        "period_end": period_end,
        "metric_name": metric_name,
        "metric_value": metric_value,
        "timestamp": timestamp,
    }


def make_prediction_event(
    *,
    event_id: str,
    deal_id: str,
    period_start: str,
    period_end: str,
    evaluation_status: EvaluationStatus,
    covenants_evaluated: int,
    breaches_count: int,
    risk_probability: float,
    risk_tier: RiskTier,
    model_version: str,
    evaluation_latency_ms: int,
    prediction_latency_ms: int,
    processed_at: str,
) -> PredictionEventV1:
    """Create a prediction event.

    Args:
        event_id: UUID for this event.
        deal_id: Deal identifier.
        period_start: ISO date for period start.
        period_end: ISO date for period end.
        evaluation_status: Deterministic evaluation result.
        covenants_evaluated: Number of covenants checked.
        breaches_count: Number of breaches detected.
        risk_probability: ML-predicted probability.
        risk_tier: Categorized risk level.
        model_version: ML model version.
        evaluation_latency_ms: Evaluation time in ms.
        prediction_latency_ms: Prediction time in ms.
        processed_at: ISO datetime of processing.

    Returns:
        PredictionEventV1 instance.
    """
    return {
        "type": "covenant.prediction.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "period_start": period_start,
        "period_end": period_end,
        "evaluation_status": evaluation_status,
        "covenants_evaluated": covenants_evaluated,
        "breaches_count": breaches_count,
        "risk_probability": risk_probability,
        "risk_tier": risk_tier,
        "model_version": model_version,
        "evaluation_latency_ms": evaluation_latency_ms,
        "prediction_latency_ms": prediction_latency_ms,
        "processed_at": processed_at,
    }


def make_alert_event(
    *,
    event_id: str,
    deal_id: str,
    alert_type: AlertType,
    severity: AlertSeverity,
    risk_probability: float,
    gemini_summary: str,
    triggered_at: str,
) -> AlertEventV1:
    """Create an alert event.

    Args:
        event_id: UUID for this event.
        deal_id: Deal identifier.
        alert_type: Category of alert.
        severity: Alert severity level.
        risk_probability: ML-predicted probability.
        gemini_summary: Human-readable summary.
        triggered_at: ISO datetime of alert.

    Returns:
        AlertEventV1 instance.
    """
    return {
        "type": "covenant.alert.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "alert_type": alert_type,
        "severity": severity,
        "risk_probability": risk_probability,
        "gemini_summary": gemini_summary,
        "triggered_at": triggered_at,
    }


# =============================================================================
# Encoder Functions
# =============================================================================


def encode_measurement_event(event: MeasurementEventV1) -> str:
    """Serialize a measurement event to JSON string.

    Args:
        event: MeasurementEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_prediction_event(event: PredictionEventV1) -> str:
    """Serialize a prediction event to JSON string.

    Args:
        event: PredictionEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_alert_event(event: AlertEventV1) -> str:
    """Serialize an alert event to JSON string.

    Args:
        event: AlertEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


def encode_kafka_event(event: KafkaEventV1) -> str:
    """Serialize any Kafka event to JSON string.

    Args:
        event: Any KafkaEventV1 to serialize.

    Returns:
        Compact JSON string.
    """
    return dump_json_str(event)


# =============================================================================
# Literal Type Parsers
# =============================================================================


def _parse_evaluation_status(raw: str) -> EvaluationStatus:
    """Parse evaluation status from string.

    Args:
        raw: Raw string value.

    Returns:
        Validated EvaluationStatus literal.

    Raises:
        JSONTypeError: If value is not valid.
    """
    if raw == "OK":
        return "OK"
    if raw == "BREACH":
        return "BREACH"
    if raw == "WARNING":
        return "WARNING"
    raise JSONTypeError(f"Invalid evaluation status '{raw}'")


def _parse_risk_tier(raw: str) -> RiskTier:
    """Parse risk tier from string.

    Args:
        raw: Raw string value.

    Returns:
        Validated RiskTier literal.

    Raises:
        JSONTypeError: If value is not valid.
    """
    if raw == "LOW":
        return "LOW"
    if raw == "MEDIUM":
        return "MEDIUM"
    if raw == "HIGH":
        return "HIGH"
    if raw == "CRITICAL":
        return "CRITICAL"
    raise JSONTypeError(f"Invalid risk tier '{raw}'")


def _parse_alert_type(raw: str) -> AlertType:
    """Parse alert type from string.

    Args:
        raw: Raw string value.

    Returns:
        Validated AlertType literal.

    Raises:
        JSONTypeError: If value is not valid.
    """
    if raw == "breach":
        return "breach"
    if raw == "high_risk":
        return "high_risk"
    raise JSONTypeError(f"Invalid alert type '{raw}'")


def _parse_alert_severity(raw: str) -> AlertSeverity:
    """Parse alert severity from string.

    Args:
        raw: Raw string value.

    Returns:
        Validated AlertSeverity literal.

    Raises:
        JSONTypeError: If value is not valid.
    """
    if raw == "warning":
        return "warning"
    if raw == "critical":
        return "critical"
    raise JSONTypeError(f"Invalid alert severity '{raw}'")


# =============================================================================
# Decoder Functions
# =============================================================================


def _decode_measurement_event(decoded: JSONObject, event_id: str) -> MeasurementEventV1:
    """Decode a measurement event from JSON object.

    Args:
        decoded: Parsed JSON object.
        event_id: Already-extracted event ID.

    Returns:
        Validated MeasurementEventV1.

    Raises:
        JSONTypeError: If required fields are missing or invalid.
    """
    deal_id = require_str(decoded, "deal_id")
    period_start = require_str(decoded, "period_start")
    period_end = require_str(decoded, "period_end")
    metric_name = require_str(decoded, "metric_name")
    metric_value = require_float(decoded, "metric_value")
    timestamp = require_str(decoded, "timestamp")
    return {
        "type": "covenant.measurement.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "period_start": period_start,
        "period_end": period_end,
        "metric_name": metric_name,
        "metric_value": metric_value,
        "timestamp": timestamp,
    }


def _decode_prediction_event(decoded: JSONObject, event_id: str) -> PredictionEventV1:
    """Decode a prediction event from JSON object.

    Args:
        decoded: Parsed JSON object.
        event_id: Already-extracted event ID.

    Returns:
        Validated PredictionEventV1.

    Raises:
        JSONTypeError: If required fields are missing or invalid.
    """
    deal_id = require_str(decoded, "deal_id")
    period_start = require_str(decoded, "period_start")
    period_end = require_str(decoded, "period_end")
    evaluation_status_raw = require_str(decoded, "evaluation_status")
    evaluation_status = _parse_evaluation_status(evaluation_status_raw)
    covenants_evaluated = require_int(decoded, "covenants_evaluated")
    breaches_count = require_int(decoded, "breaches_count")
    risk_probability = require_float(decoded, "risk_probability")
    risk_tier_raw = require_str(decoded, "risk_tier")
    risk_tier = _parse_risk_tier(risk_tier_raw)
    model_version = require_str(decoded, "model_version")
    evaluation_latency_ms = require_int(decoded, "evaluation_latency_ms")
    prediction_latency_ms = require_int(decoded, "prediction_latency_ms")
    processed_at = require_str(decoded, "processed_at")
    return {
        "type": "covenant.prediction.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "period_start": period_start,
        "period_end": period_end,
        "evaluation_status": evaluation_status,
        "covenants_evaluated": covenants_evaluated,
        "breaches_count": breaches_count,
        "risk_probability": risk_probability,
        "risk_tier": risk_tier,
        "model_version": model_version,
        "evaluation_latency_ms": evaluation_latency_ms,
        "prediction_latency_ms": prediction_latency_ms,
        "processed_at": processed_at,
    }


def _decode_alert_event(decoded: JSONObject, event_id: str) -> AlertEventV1:
    """Decode an alert event from JSON object.

    Args:
        decoded: Parsed JSON object.
        event_id: Already-extracted event ID.

    Returns:
        Validated AlertEventV1.

    Raises:
        JSONTypeError: If required fields are missing or invalid.
    """
    deal_id = require_str(decoded, "deal_id")
    alert_type_raw = require_str(decoded, "alert_type")
    alert_type = _parse_alert_type(alert_type_raw)
    severity_raw = require_str(decoded, "severity")
    severity = _parse_alert_severity(severity_raw)
    risk_probability = require_float(decoded, "risk_probability")
    gemini_summary = require_str(decoded, "gemini_summary")
    triggered_at = require_str(decoded, "triggered_at")
    return {
        "type": "covenant.alert.v1",
        "event_id": event_id,
        "deal_id": deal_id,
        "alert_type": alert_type,
        "severity": severity,
        "risk_probability": risk_probability,
        "gemini_summary": gemini_summary,
        "triggered_at": triggered_at,
    }


# Decoder dispatch table
_DECODERS: dict[str, Callable[[JSONObject, str], KafkaEventV1]] = {
    "covenant.measurement.v1": _decode_measurement_event,
    "covenant.prediction.v1": _decode_prediction_event,
    "covenant.alert.v1": _decode_alert_event,
}


def decode_measurement_event(payload: str) -> MeasurementEventV1:
    """Parse and validate a measurement event from JSON string.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated MeasurementEventV1.

    Raises:
        JSONTypeError: If payload is not a valid measurement event.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    type_raw = require_str(decoded, "type")
    if type_raw != "covenant.measurement.v1":
        raise JSONTypeError(f"Expected measurement event, got type '{type_raw}'")
    event_id = require_str(decoded, "event_id")
    return _decode_measurement_event(decoded, event_id)


def decode_prediction_event(payload: str) -> PredictionEventV1:
    """Parse and validate a prediction event from JSON string.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated PredictionEventV1.

    Raises:
        JSONTypeError: If payload is not a valid prediction event.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    type_raw = require_str(decoded, "type")
    if type_raw != "covenant.prediction.v1":
        raise JSONTypeError(f"Expected prediction event, got type '{type_raw}'")
    event_id = require_str(decoded, "event_id")
    return _decode_prediction_event(decoded, event_id)


def decode_alert_event(payload: str) -> AlertEventV1:
    """Parse and validate an alert event from JSON string.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated AlertEventV1.

    Raises:
        JSONTypeError: If payload is not a valid alert event.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    type_raw = require_str(decoded, "type")
    if type_raw != "covenant.alert.v1":
        raise JSONTypeError(f"Expected alert event, got type '{type_raw}'")
    event_id = require_str(decoded, "event_id")
    return _decode_alert_event(decoded, event_id)


def decode_kafka_event(payload: str) -> KafkaEventV1:
    """Parse and validate any Kafka event from JSON string.

    Automatically detects event type from 'type' field and dispatches
    to the appropriate decoder.

    Args:
        payload: JSON string to parse.

    Returns:
        Validated KafkaEventV1 (one of the three event types).

    Raises:
        JSONTypeError: If payload is not a valid Kafka event.
    """
    decoded = narrow_json_to_dict(load_json_str(payload))
    type_raw = require_str(decoded, "type")
    event_id = require_str(decoded, "event_id")

    decoder = _DECODERS.get(type_raw)
    if decoder is None:
        raise JSONTypeError(f"Unknown Kafka event type: '{type_raw}'")
    return decoder(decoded, event_id)


# =============================================================================
# TypeGuard Functions
# =============================================================================


def is_measurement_event(event: KafkaEventV1) -> TypeGuard[MeasurementEventV1]:
    """Check if event is a measurement event.

    Args:
        event: Any KafkaEventV1 to check.

    Returns:
        True if event is MeasurementEventV1.
    """
    return event.get("type") == "covenant.measurement.v1"


def is_prediction_event(event: KafkaEventV1) -> TypeGuard[PredictionEventV1]:
    """Check if event is a prediction event.

    Args:
        event: Any KafkaEventV1 to check.

    Returns:
        True if event is PredictionEventV1.
    """
    return event.get("type") == "covenant.prediction.v1"


def is_alert_event(event: KafkaEventV1) -> TypeGuard[AlertEventV1]:
    """Check if event is an alert event.

    Args:
        event: Any KafkaEventV1 to check.

    Returns:
        True if event is AlertEventV1.
    """
    return event.get("type") == "covenant.alert.v1"


# =============================================================================
# Re-exports from covenant_domain
# =============================================================================
# RiskTier and classify_risk_tier are imported from covenant_domain.features
# and re-exported here for convenience.


__all__ = [
    "AlertEventType",
    "AlertEventV1",
    "AlertSeverity",
    "AlertType",
    "EvaluationStatus",
    "KafkaEventType",
    "KafkaEventV1",
    "MeasurementEventType",
    "MeasurementEventV1",
    "PredictionEventType",
    "PredictionEventV1",
    "RiskTier",
    "classify_risk_tier",
    "decode_alert_event",
    "decode_kafka_event",
    "decode_measurement_event",
    "decode_prediction_event",
    "encode_alert_event",
    "encode_kafka_event",
    "encode_measurement_event",
    "encode_prediction_event",
    "is_alert_event",
    "is_measurement_event",
    "is_prediction_event",
    "make_alert_event",
    "make_measurement_event",
    "make_prediction_event",
]
