"""Tests for ``format_fuel_probe_summary``.

One table-driven test over every terminal status the summary counts.
"""

from __future__ import annotations

from tests.action_lab._fuel_probe_harness import (
    _snapshot,
)

from tankpit_bot.action_lab.fuel_probe_diagnostics import format_fuel_probe_summary
from tankpit_bot.action_lab.fuel_probe_types import (
    FuelProbeAttemptResultDict,
    FuelProbeSessionDict,
)


def test_format_fuel_probe_summary_counts_statuses() -> None:
    """Fuel probe summary reports all terminal status buckets."""
    session = FuelProbeSessionDict(
        session_id="fuel-session",
        start_timestamp_ms=100,
        end_timestamp_ms=200,
        base_url="https://tankpit.com/play",
        spawn_x=100,
        spawn_y=100,
        target_pickups=3,
        max_attempts=6,
        capture_session_path="fuel_probe.capture_session.json",
        initial_sync_timeout_ms=10000,
        startup_timing={
            "game_ready_timestamp_ms": 300,
            "intel_ready_timestamp_ms": 350,
            "initial_sync_started_ms": 400,
            "initial_world_timestamp_ms": 450,
            "command_ready_timestamp_ms": 460,
            "first_attempt_started_ms": 500,
            "game_ready_to_intel_ready_ms": 50,
            "intel_ready_to_initial_world_ms": 100,
            "initial_world_to_command_ready_ms": 10,
            "command_ready_to_first_attempt_ms": 40,
        },
        map_sync_timeout_ms=3000,
        teleport_timeout_ms=10000,
        radar_timeout_ms=3000,
        pickup_timeout_ms=3000,
        settle_delay_ms=500,
        attempts=[
            FuelProbeAttemptResultDict(
                target={"label": "a", "x": 1, "y": 1},
                teleport_cycle_ids=[1],
                radar_cycle_id=None,
                move_cycle_id=None,
                pickup_cycle_id=None,
                status="picked_up_fuel",
                map_open_started_ms=1000,
                map_sync_timestamp_ms=1100,
                teleport_started_ms=1200,
                radar_started_ms=1300,
                radar_sync_timestamp_ms=1400,
                reposition_map_open_started_ms=None,
                reposition_map_sync_timestamp_ms=None,
                reposition_teleport_started_ms=None,
                pickup_started_ms=1500,
                completion_timestamp_ms=1600,
                fuel_before=500,
                fuel_after=700,
                landed_signal_received=True,
                landed_x=1,
                landed_y=1,
                fuel_target_x=2,
                fuel_target_y=1,
                fuel_target_volume=200,
                phase_overlaps=[],
                decision_basis=None,
                snapshot_before=_snapshot(0),
                snapshot_after=_snapshot(0),
                message_start_index=0,
                message_end_index=1,
            ),
            FuelProbeAttemptResultDict(
                target={"label": "b", "x": 2, "y": 2},
                teleport_cycle_ids=[1],
                radar_cycle_id=None,
                move_cycle_id=None,
                pickup_cycle_id=None,
                status="no_fuel_visible",
                map_open_started_ms=1000,
                map_sync_timestamp_ms=1100,
                teleport_started_ms=1200,
                radar_started_ms=1300,
                radar_sync_timestamp_ms=1400,
                reposition_map_open_started_ms=None,
                reposition_map_sync_timestamp_ms=None,
                reposition_teleport_started_ms=None,
                pickup_started_ms=None,
                completion_timestamp_ms=1600,
                fuel_before=500,
                fuel_after=500,
                landed_signal_received=True,
                landed_x=2,
                landed_y=2,
                fuel_target_x=None,
                fuel_target_y=None,
                fuel_target_volume=None,
                phase_overlaps=[],
                decision_basis=None,
                snapshot_before=_snapshot(0),
                snapshot_after=_snapshot(0),
                message_start_index=1,
                message_end_index=2,
            ),
            FuelProbeAttemptResultDict(
                target={"label": "c", "x": 3, "y": 3},
                teleport_cycle_ids=[1],
                radar_cycle_id=None,
                move_cycle_id=None,
                pickup_cycle_id=None,
                status="radar_timeout",
                map_open_started_ms=1000,
                map_sync_timestamp_ms=1100,
                teleport_started_ms=1200,
                radar_started_ms=1300,
                radar_sync_timestamp_ms=None,
                reposition_map_open_started_ms=None,
                reposition_map_sync_timestamp_ms=None,
                reposition_teleport_started_ms=None,
                pickup_started_ms=None,
                completion_timestamp_ms=1600,
                fuel_before=500,
                fuel_after=450,
                landed_signal_received=True,
                landed_x=3,
                landed_y=3,
                fuel_target_x=None,
                fuel_target_y=None,
                fuel_target_volume=None,
                phase_overlaps=[],
                decision_basis=None,
                snapshot_before=_snapshot(0),
                snapshot_after=_snapshot(0),
                message_start_index=2,
                message_end_index=3,
            ),
            FuelProbeAttemptResultDict(
                target={"label": "d", "x": 4, "y": 4},
                teleport_cycle_ids=[1],
                radar_cycle_id=None,
                move_cycle_id=None,
                pickup_cycle_id=None,
                status="map_sync_timeout",
                map_open_started_ms=1000,
                map_sync_timestamp_ms=None,
                teleport_started_ms=None,
                radar_started_ms=None,
                radar_sync_timestamp_ms=None,
                reposition_map_open_started_ms=None,
                reposition_map_sync_timestamp_ms=None,
                reposition_teleport_started_ms=None,
                pickup_started_ms=None,
                completion_timestamp_ms=1600,
                fuel_before=500,
                fuel_after=500,
                landed_signal_received=False,
                landed_x=4,
                landed_y=4,
                fuel_target_x=None,
                fuel_target_y=None,
                fuel_target_volume=None,
                phase_overlaps=[],
                decision_basis=None,
                snapshot_before=_snapshot(0),
                snapshot_after=_snapshot(0),
                message_start_index=3,
                message_end_index=4,
            ),
            FuelProbeAttemptResultDict(
                target={"label": "e", "x": 5, "y": 5},
                teleport_cycle_ids=[1],
                radar_cycle_id=None,
                move_cycle_id=None,
                pickup_cycle_id=None,
                status="teleport_timeout",
                map_open_started_ms=1000,
                map_sync_timestamp_ms=1100,
                teleport_started_ms=1200,
                radar_started_ms=None,
                radar_sync_timestamp_ms=None,
                reposition_map_open_started_ms=None,
                reposition_map_sync_timestamp_ms=None,
                reposition_teleport_started_ms=None,
                pickup_started_ms=None,
                completion_timestamp_ms=1600,
                fuel_before=500,
                fuel_after=450,
                landed_signal_received=False,
                landed_x=5,
                landed_y=5,
                fuel_target_x=None,
                fuel_target_y=None,
                fuel_target_volume=None,
                phase_overlaps=[],
                decision_basis=None,
                snapshot_before=_snapshot(0),
                snapshot_after=_snapshot(0),
                message_start_index=4,
                message_end_index=5,
            ),
            FuelProbeAttemptResultDict(
                target={"label": "f", "x": 6, "y": 6},
                teleport_cycle_ids=[1],
                radar_cycle_id=None,
                move_cycle_id=None,
                pickup_cycle_id=None,
                status="pickup_timeout",
                map_open_started_ms=1000,
                map_sync_timestamp_ms=1100,
                teleport_started_ms=1200,
                radar_started_ms=1300,
                radar_sync_timestamp_ms=1400,
                reposition_map_open_started_ms=None,
                reposition_map_sync_timestamp_ms=None,
                reposition_teleport_started_ms=None,
                pickup_started_ms=1500,
                completion_timestamp_ms=1600,
                fuel_before=500,
                fuel_after=450,
                landed_signal_received=True,
                landed_x=6,
                landed_y=6,
                fuel_target_x=7,
                fuel_target_y=6,
                fuel_target_volume=200,
                phase_overlaps=[],
                decision_basis=None,
                snapshot_before=_snapshot(0),
                snapshot_after=_snapshot(0),
                message_start_index=5,
                message_end_index=6,
            ),
        ],
    )

    summary = format_fuel_probe_summary(session)

    assert "attempts=6" in summary
    assert "target_pickups=3" in summary
    assert "picked_up_fuel=1" in summary
    assert "no_fuel_visible=1" in summary
    assert "radar_timeout=1" in summary
    assert "map_sync_timeout=1" in summary
    assert "teleport_timeout=1" in summary
    assert "pickup_timeout=1" in summary
    assert "session_to_initial_sync_ms=300" in summary
    assert "initial_sync_to_command_ready_ms=60" in summary
