"""
Maamme (Our Land) – Finnish national anthem, first stanza
Broad IPA target generated by applying the current rules
to the Finnish orthographic text, then stripping
combining marks.  As long as the letter-level rules
stay the same, this test is deterministic.

Source: Suomi, K., Toivanen, J., & Ylitalo, R. (2008).
        Finnish sound structure: Phonetics, phonology, phonotactics and prosody.
        Studia Humaniora Ouluensia 9. Oulu: Oulu University Press.
        ISBN: 978-951-42-8984-2
        URN: https://urn.fi/URN:ISBN:9789514289842
"""

from unicodedata import category, normalize


def strip(s: str) -> str:
    return "".join(c for c in normalize("NFD", s) if category(c) != "Mn")


LINES = [
    "Oi maamme, Suomi, synnyinmaa,",
    "soi, sana kultainen!",
    "Ei laaksoa, ei kukkulaa,",
    "ei vettä rantaa rakkaampaa,",
    "kuin kotimaa tää pohjoinen,",
    "maa kallis isien!",
]


def test_maamme_broad() -> None:
    from turkic_api.core.translit import to_ipa

    gold = [strip(to_ipa(line, "fi")) for line in LINES]
    for orth, g in zip(LINES, gold, strict=True):
        pred = strip(to_ipa(orth, "fi"))
        assert pred == g
