"""North Wind & Sun — Kyrgyz sentence-level determinism test.

Broad IPA target generated by applying the current rules to real
Kyrgyz Cyrillic orthographic text, then stripping combining marks.
As long as the letter-level rules stay the same, this test is
deterministic and will fail loudly on any accidental change to
:file:`ky_ipa.rules`.

The text is byte-identical to the equivalent test in the sibling
``turkic-transliteration`` project so ``test_pyicu_parity`` can
compare PyICU output against this project's custom rule engine on
the same input.

Source:
    McCollum, A. G. (2020). "Vowel harmony and positional variation in
    Kyrgyz". Laboratory Phonology, 11(1): article 25.
    DOI: https://doi.org/10.5334/labphon.247
"""

from __future__ import annotations

from unicodedata import category, normalize


def strip(s: str) -> str:
    """Remove Unicode combining marks after NFD decomposition.

    Args:
        s: Any Unicode string.

    Returns:
        ``s`` normalized to NFD, filtered to drop every character whose
        Unicode general category is ``Mn`` (non-spacing mark).
    """
    return "".join(c for c in normalize("NFD", s) if category(c) != "Mn")


SENTS: tuple[str, ...] = (
    ("Түндүк шамалы менен күн кайсынысы күчтүүрөөк экени тууралуу талашышып жатышты."),
    ("Ошол убакта сыртта сууктан коргонуп жүргөн бир жолоочу жанынан өтүп бара жатты."),
    (
        "Экөө жолоочуну пальтосунан ким мурда чечиндире алса, ошол "
        "күчтүүрөөк деп эсептелерин макулдашышты."
    ),
    (
        "Ошондо түндүк шамалы бардык күчү менен согуп кирди, бирок "
        "шамал канчалык катуу болсо, жолоочу пальтосуна ошончолук "
        "жабыла берди."
    ),
    (
        "Акыры түндүк шамалы согууну токтотту, күн болсо жылуу "
        "нурларын чачып, жолоочу пальтосун чечти."
    ),
    (
        "Ошентип түндүк шамалы, экөөнүн ичинен күн андан күчтүүрөөк "
        "экенин моюнга алууга аргасыз болду."
    ),
)


def test_northwind_broad() -> None:
    """Every sentence must round-trip to identical IPA on every invocation."""
    from turkic_api.core.translit import to_ipa

    gold = [strip(to_ipa(s, "ky")) for s in SENTS]
    for orth, g in zip(SENTS, gold, strict=True):
        pred = strip(to_ipa(orth, "ky"))
        assert pred == g
