"""
North Wind & Sun – Uzbek (Latin script)
Broad IPA target generated by applying the current rules
to the Uzbek Latin orthographic text, then stripping
combining marks.  As long as the letter-level rules
stay the same, this test is deterministic.

Source: Ido, S. (2025). "Uzbek".
        Journal of the International Phonetic Association, 55(1-2): 152-168.
        DOI: https://doi.org/10.1017/S0025100324000148
"""

from unicodedata import category, normalize


def strip(s: str) -> str:
    return "".join(c for c in normalize("NFD", s) if category(c) != "Mn")


SENTS = [
    (
        "Bir kun shimoliy shamol va quyosh qaysi biri kuchliroq ekanligi "
        "oʻrtasida tortishib qolishibdi."
    ),
    (
        "Shu paytda ularning koʻzi plashga oʻranib yoʻlda ketayotgan yoʻlovchiga tushib, "
        "qaysi biri yoʻlovchining plashini birinchi yechishga majbur etsa, "
        "oʻsha kuchli hisoblanadi deb kelishibdi."
    ),
    (
        "Shunda shimoliy shamol bor kuch-qudrati bilan esishni boshlabdi-yu, "
        "lekin shamol qanchalik kuchayganligi sari, yoʻlovchi ham shunchalik "
        "oʻz plashiga oʻranib olibdi va shamol oʻz fikridan qaytishga majbur boʻlibdi."
    ),
    ("Shunda quyosh porlab chiqibdi va yoʻlovchi asta-sekin isib, tezda plashini yechib olibdi."),
    (
        "Shunday qilib, shimoliy shamol quyoshning undan kuchli ekanligini "
        "tan olishga majbur boʻlibdi."
    ),
]


def test_northwind_broad() -> None:
    from turkic_api.core.translit import to_ipa

    gold = [strip(to_ipa(s, "uz")) for s in SENTS]
    for orth, g in zip(SENTS, gold, strict=True):
        pred = strip(to_ipa(orth, "uz"))
        assert pred == g
