"""
North Wind & Sun – Azerbaijani
Broad IPA target generated by applying the current rules
to the Azerbaijani orthographic text, then stripping
combining marks.  As long as the letter-level rules
stay the same, this test is deterministic.

Source: Ghaffarvand Mokari, P. & Werner, S. (2017). "Azerbaijani".
        Journal of the International Phonetic Association, 47(2): 207–212.
        DOI: https://doi.org/10.1017/S0025100317000184
"""

from unicodedata import category, normalize


def strip(s: str) -> str:
    return "".join(c for c in normalize("NFD", s) if category(c) != "Mn")


SENTS = [
    "Şimal yeli ilə Günəş mübahisə edirdilər ki, hansı daha güclüdür.",
    "O zaman bir isti əbaya bürünmüş səyahətçi oradan keçirdi.",
    (
        "Belə anlaşdılar ki, hər hansı əvvəldə bəcərdi səyahətçinin əbasını çıxarda, "
        "o birisindən daha güclüdür."
    ),
    "O zaman Şimal yeli bəcərdiyi qədər əsməyə başladı.",
    "Amma hər nə qədər artıq əsdikcə, səyahətçi də əbasını dərəsinə bürüyürdü.",
    "Sonda Şimal yeli əsməyi buraxdı.",
    "Sonra Günəş isti şəfəqlənməyə başladı və bilavasitə səyahətçi əbasını çıxartdı.",
    "Və Şimal yeli məcbur oldu etiraf eliyə ki, Günəş ikisinin arasında daha güclüdür.",
]


def test_northwind_broad() -> None:
    from turkic_api.core.translit import to_ipa

    gold = [strip(to_ipa(s, "az")) for s in SENTS]
    for orth, g in zip(SENTS, gold, strict=True):
        pred = strip(to_ipa(orth, "az"))
        assert pred == g
