"""
North Wind & Sun passage in Russian.

Broad IPA target generated by applying the current rules to the orthographic
text from Yanushevskaya & Bunčić (2015). The article provides both the
Cyrillic orthography and the IPA transcription.

Source: Yanushevskaya, I. & Bunčić, D. (2015). "Russian".
        Journal of the International Phonetic Association, 45(2): 221-228.
        DOI: https://doi.org/10.1017/S0025100314000395

Note: The article's transcription includes stress marks and phonological
processes (vowel reduction, etc.) that our simplified orthographic rules
do not capture. This test validates the basic grapheme-to-phoneme mapping.
"""

from unicodedata import category, normalize


def strip_combining(s: str) -> str:
    """Remove combining marks (stress, length, etc.) for comparison."""
    return "".join(c for c in normalize("NFD", s) if category(c) != "Mn")


# Full orthographic text from the JIPA article (p. 226)
# fmt: off
ORTHOGRAPHIC = (
    "Однажды северный ветер и солнце поспорили, кто из них сильнее. "
    "Как раз в это время они заметили закутанного в плащ путника, "
    "который шёл по дороге, и решили, что тот из них будет считаться "
    "самым сильным, кому раньше удастся заставить путника снять плащ. "
    "Тут северный ветер принялся дуть изо всех сил; но чем сильнее он дул, "
    "тем сильнее кутался путник в свой плащ, так что в конце концов "
    "северный ветер должен был отказаться от своей затеи. "
    "Тогда засияло солнышко, путник понемногу отогрелся и вскоре снял свой плащ. "
    "Таким образом, северный ветер вынужден был признать, что солнце сильнее его."
)
# fmt: on

# Individual sentences for granular testing
SENTENCES = [
    "Однажды северный ветер и солнце поспорили, кто из них сильнее.",
    (
        "Как раз в это время они заметили закутанного в плащ путника, "
        "который шёл по дороге, и решили, что тот из них будет считаться "
        "самым сильным, кому раньше удастся заставить путника снять плащ."
    ),
    (
        "Тут северный ветер принялся дуть изо всех сил; но чем сильнее он дул, "
        "тем сильнее кутался путник в свой плащ, так что в конце концов "
        "северный ветер должен был отказаться от своей затеи."
    ),
    "Тогда засияло солнышко, путник понемногу отогрелся и вскоре снял свой плащ.",
    "Таким образом, северный ветер вынужден был признать, что солнце сильнее его.",
]


def test_northwind_deterministic() -> None:
    """Verify that the transcription is deterministic (same input → same output)."""
    from turkic_api.core.translit import to_ipa

    # Run twice and compare
    result1 = strip_combining(to_ipa(ORTHOGRAPHIC, "ru"))
    result2 = strip_combining(to_ipa(ORTHOGRAPHIC, "ru"))
    assert result1 == result2


def test_northwind_sentences() -> None:
    """Transcribe each sentence and verify basic properties."""
    from turkic_api.core.translit import to_ipa

    for sent in SENTENCES:
        ipa = to_ipa(sent, "ru")
        # Should not contain any Cyrillic letters
        for char in ipa:
            assert not ("\u0400" <= char <= "\u04ff"), f"Cyrillic {char!r} in output"
        # Should produce non-empty output (input has content)
        assert ipa, f"Empty IPA output for: {sent[:30]!r}..."


def test_northwind_key_words() -> None:
    """Check specific words from the passage against expected IPA."""
    from turkic_api.core.translit import to_ipa

    # Key words extracted from the passage with expected IPA
    # Based on our rule mappings (simplified, no vowel reduction)
    key_words = {
        "северный": "sjevjernɨj",  # 'northern'
        "ветер": "vjetjer",  # 'wind'
        "солнце": "solnt͡sje",  # 'sun'
        "сильнее": "silʲnjeje",  # 'stronger'
        "плащ": "plaʃʲː",  # 'cloak'
        "путник": "putnik",  # 'traveler'
        "дуть": "dutʲ",  # 'to blow'
        "снять": "snjatʲ",  # 'to take off'
    }

    for word, expected in key_words.items():
        actual = to_ipa(word, "ru")
        assert actual == expected, f"{word!r}: expected {expected!r}, got {actual!r}"
