"""
North-Wind & Sun - sentences 1-3
Broad IPA target generated by applying the current rules
to McCollum & Chen's Cyrillic text, then stripping
combining marks. As long as the letter-level rules
stay the same, this test is deterministic.

Source: McCollum, A. G. & Chen, S. (2021). "Kazakh".
        Journal of the International Phonetic Association, 51(2): 276-298.
        DOI: https://doi.org/10.1017/S0025100319000185
"""

from unicodedata import category, normalize


def strip(s: str) -> str:
    return "".join(c for c in normalize("NFD", s) if category(c) != "Mn")


SENTS = [
    "Бір күні солтүстік жел мен күн екеуі араларында кім мықты екенін шеше алмай бәсікелеседі.",
    "Дәл осы мезетте жол бойында шапанға оранып келе жатқан жолаушыны кезіктіреді.",
    (
        "Екеуіне ой келеді, кім де кім жолаушыға үстіндегі "
        "шапанын шешкізе алса, сол мықты деген шешімге келеді."
    ),
]


def test_northwind_broad() -> None:
    from turkic_api.core.translit import to_ipa

    gold = [strip(to_ipa(s, "kk")) for s in SENTS]
    for orth, g in zip(SENTS, gold, strict=True):
        pred = strip(to_ipa(orth, "kk"))
        assert pred == g
